### ISSUE TITLE
Homepage search result is URI encoded

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#998] opened 2016-04-06 23:35 UTC
STR:

1) Go to webcompat.com
2) click search in top nav bar
3) search for "http://google.com"

Expected:
You go to the issues page with "http://google.com" in the seach input

Actual:
You get `http%3A%2F%2Fgoogle.com%2F`

@dshgna want to take a look? We probably just need to call `decodeURIComponent` or something on the input when the page is loaded from a search query.

**Comment by dshgna** [comment] 2016-04-07 02:38
@miketaylr sure... will get started on this!

**Comment by karlcow** [comment] 2016-04-07 02:50
1. Go to all issues
2. Search http://www.google.com/
    
`https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=http%3A%2F%2Fwww.google.com`

Working. So this is happening only in the home page.

On the home page, the string is:

`https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=http%253A%252F%252Fgoogle.com`

to make it more explicit:

* `q=http%253A%252F%252Fgoogle.com` (bad)
* `q=http%3A%2F%2Fwww.google.com` (good)

**Comment by miketaylr** [comment] 2016-04-28 21:05
I think I'm going to take over this bug.

**Comment by miketaylr** [comment] 2017-04-26 08:53
To check if this was fixed by #1518 -- @magsout would you mind?

**Comment by miketaylr** [comment] 2017-04-26 08:54
Ping @zoepage

**Comment by magsout** [comment] 2017-04-26 09:04
@miketaylr I 'll check

**Comment by magsout** [comment] 2017-04-26 18:57
### test:
    Go to webcompat.com
    click search in top nav bar
    search for "http://google.com"

result:  https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=%22http%3A%2F%2Fgoogle.com%22

![capture d ecran 2017-04-26 a 20 53 58](https://cloud.githubusercontent.com/assets/1997108/25451442/7d1b1a4a-2ac2-11e7-8c73-6ea74672be0f.png)


### test: 

     goto:  https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=%22http%3A%2F%2Fgoogle.com%22
     refresh

result: 
![capture d ecran 2017-04-26 a 20 53 58](https://cloud.githubusercontent.com/assets/1997108/25451442/7d1b1a4a-2ac2-11e7-8c73-6ea74672be0f.png)


I can't reproduce the bug, it's well fixed by #1518

**Closed by magsout** 2017-04-26 18:57 UTC
Labels: lang: JS, type: bug
