### ISSUE TITLE
Unexpected behaviour of "Upload a different image" [New UI]

### ISSUE THREAD

**Issue by mcroud** [webcompat/webcompat.com#2983] opened 2019-10-14 17:29 UTC
On step 6 (Screenshot), if I upload an image and then click to **Upload a different image**, the screenshot is deleted and I am taken back up to the very top of the page.

![Untitled5](https://user-images.githubusercontent.com/42435754/66770591-f0e90000-eeaf-11e9-88db-8d7deb8d9c2b.gif)

My expectation as a user would be to be presented with another Open file dialogue to select a different image without going through the process of deleting the current image.

**Comment by munteanu210** [comment] 2019-10-15 20:18
@mcroud, thanks for your review. Here is [a video how](https://drive.google.com/file/d/1k1wQTBPRd1z7MXkD32SLOJml6_iWf9Hv/view) this works on my machine.

This issue is fixed in the updates submitted in [this PR](https://github.com/webcompat/webcompat.com/pull/2942). However, I would recommend reviewing this issue again once [pull request](https://github.com/webcompat/webcompat.com/pull/2984) with the mobile view is approved, merged, and the staging / dev site is updated.

I am saying this, because it seems to me the staging / dev site wasn't updated with my latest updates. I want to make sure both PRs from above reach the master branch, and only after that, the staging / dev site is updated to contain everything.

**Comment by mcroud** [comment] 2019-10-16 08:24
@munteanu210 Thanks for the heads up, I will absolutely check it out again.

**Comment by mcroud** [comment] 2019-10-22 11:55
Hi @munteanu210, just reviewing this on mobile...

It seems to me that clicking "Upload a different image" has the same effect as "Delete this image", clicking both deletes the image.

The desired effect of "Upload a different image" is that it opens up the "Select file" dialogue WITHOUT deleting the image first. If a new image is selected than this will replace the previous image, if the "Select file" dialogue is closed than the previous image remains. 
Please let me know if I've done a poor job at describing this :D

**Comment by munteanu210** [comment] 2019-10-22 19:00
@mcroud, I understood what the problem is. Thanks for identifying it. I fixed it in PR #3011.

**Closed** 2019-10-22 20:39 UTC
