### ISSUE TITLE
A loading spinner or message should be displayed when performing a “Search”

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#2340] opened 2018-03-29 06:55 UTC
URL: www.staging.webcompat.com, www.webcompat.com 
Browser / Version: Firefox Nightly 61.0a1 (2018-03-28), Chrome 65.0.3325.181
Operating System: Windows 10 Pro

**Steps to Reproduce:**
    1. Navigate to https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc 
    2. Tap the “Search” field and type in a keyword (e.g. test).
    3. Observe behavior while results are fetched.
       
**Expected Behavior:**
A loading spinner or message (e.g “Searching...”) are displayed.

**Actual Behavior:**
Empty results page is displayed and no loading spinners or message are displayed.

**Note**
    1. Also reproducible when clicking labels.
        
**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv; 

![image](https://user-images.githubusercontent.com/12184325/38075030-8ed7104c-3339-11e8-932f-b76a4fd51f8e.png)

![noloadingspinner](https://user-images.githubusercontent.com/12184325/38074196-9e309d40-3336-11e8-9926-fa4281e88354.gif)

**Comment by zoepage** [comment] 2018-03-29 07:10
Duplicate of #1527

**Comment by karlcow** [comment] 2018-10-01 09:11
Possibly it was fixed. We don't know currently because the UI is reactive. We get the results quite fast. @softvision-oana-arbuzov what you think?

**Comment by softvision-oana-arbuzov** [comment] 2018-10-01 11:56
@karlcow yes the issue was fixed and results are return very fast.

We can consider this Closed as Fixed.

**Comment by karlcow** [comment] 2018-10-01 12:37
@softvision-oana-arbuzov Thanks. ❤️

**Closed** 2018-10-01 12:38 UTC
Labels: type: bug
