### ISSUE TITLE
button back toggles labels on issue list

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1288] opened 2017-01-17 13:04 UTC
1. https://webcompat.com -> scroll down to "Join The Team".
2. Click on either "diagnose bugs" or "reach out to sites"
3. push back button
4. Label / filter is deactivated
5. push back button
6. Label / filter is activated
7. ...

**Comment by karlcow** [comment] 2017-01-17 13:34
confirmed!

**Comment by karlcow** [comment] 2017-01-17 13:34
Discussion started on #569

**Comment by magsout** [comment] 2017-01-19 18:57
hum I don't know if it's really a bug. because 

1)https://webcompat.com/issues?stage=needsdiagnosis  first entry in history
2) https://webcompat.com/issues?page=1&per_page=50&state=open&stage=needsdiagnosis&sort=created&direction=desc second entry in history

Two url, two entry in history.

**Comment by magsout** [comment] 2017-01-19 18:59
wrong diagnosis.

-1) first entry https://webcompat.com/issues?page=1&per_page=50&state=open&stage=needsdiagnosis&sort=created&direction=desc
-2) second entry https://webcompat.com/issues?page=1&per_page=50&state=open&stage=needsdiagnosis&sort=created&direction=desc

ok, it's a BUG 💃

**Comment by miketaylr** [comment] 2017-02-01 18:14
Possibly I can fix this in the fix for #793. Will try to at least.

**Comment by miketaylr** [comment] 2017-02-01 18:16
> Possibly I can fix this in the fix for #793. Will try to at least.

Actually, yes. Let's close here as a dupe of the same underlying problem of #793.

**Closed by miketaylr** 2017-02-01 18:16 UTC
Labels: type: bug
