### ISSUE TITLE
Document invalid bugs for new contributors

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat.com#1175] opened 2016-09-13 21:51 UTC
Documenting @miketaylr's idea:
It might be useful for new contributors to see what invalid issues look like and possible avoid reporting. Maybe put into the repo wiki and link to it from the contributors page.

**Comment by miketaylr** [comment] 2016-09-14 12:36
(and we should do it in a way that doesn't blame people, aka let's not point to actual invalid bugs, but generalize over them, using similar types of bugs for example.com, etc.)

**Comment by tsl143** [comment] 2016-09-14 16:02
@miketaylr @adamopenweb @karlcow In addition to this, can we have a label for `Layout issues`. These issues may be compatibility issue or may be not. But we can actually have track of these.

**Comment by karlcow** [comment] 2016-09-14 23:40
@tsl143 could you open a new issue with the list of categories you think are worth tracking, and defining the scope of each of them would be useful too. So we share a common understanding.

**Comment by karlcow** [comment] 2016-09-14 23:50
About @adamopenweb issue

Starting fleshing out a list of problem types.

* **Reproducible everywhere**: If an issue is the same in all browsers. This is not a Web Compatibility issue.
* **Tracking Protection / Ads Blocker / Cookies blocker**: All of these are not Web Compatibility issues because the site is working correctly without them, be in Firefox or other browsers. These are choices that users might have made and which they had forgotten.
* **Fake profile/Abusive behaviors**: A site which is being abusive, a scam, a fake profile are not web compatibility issues. There are no differences in between browsers.
* **No Mobile site**: When the site doesn't provide a mobile on any browsers, then it's probably not a Web Compatibility issue, but just that the site doesn't care enough.
* **Flash Required**: A Web site requires flash in every browser for having a satisfying user experience is not a Web Compatibility issue. But a Web site which is for example providing a working video in one browser A without flash and requires Flash for another browser B with the same capabilities is a Web Compatibility issue.

## Difficult issues

* **Not usable for disability X**: A web site which is not working in jaws, VoiceOver, or any specific browsers targeting users with disabilities are indeed Web Compatibility issues. It doesn't work in this browser X, but are very hard to solve for our team and specifically do outreach for it.

**Comment by miketaylr** [comment] 2016-09-16 15:31
Digging @karlcow's list.

Maybe also we should throw in how a potentially valid bug can be closed as invalid due to lack of actionable information.

**Comment by tsl143** [comment] 2016-09-21 05:56
I think following tags can help us to club/identify many similar issues

- **Layout Issue** - any thing related to placement of elements, but looks same on all browsers

- **No Video** - as the label name says video is not played.

- **Not mobile friendly** - Bugs like Desktop website on mobile, or website not optimized for mobile layout (I am not sure if we should include the user agent detection for Firefox failure in this or not )

**Comment by miketaylr** [comment] 2016-09-23 09:36
I added a wiki page here: edits welcome!

https://github.com/webcompat/webcompat.com/wiki/Invalid-Bugs

**Closed** 2016-09-23 14:21 UTC
