### ISSUE TITLE
OAuth grant unclear

### ISSUE THREAD

**Issue by annevk** [webcompat/webcompat.com#3075] opened 2019-11-05 09:35 UTC
To "Authorize webcompat.com issues" it seems to need access to public repositories, which then also lists all organizations one is a member of, some which allow that and some which do not.

Even though it's probably fine, it did deter me from filing an issue.

(Happy to share the OAuth screenshot in private if this is unclear.)

**Comment by miketaylr** [comment] 2019-11-05 22:00
Thanks @annevk -- yeah, I agree the current OAuth flow is crappy. #655 is probably the closest issue here. In a nutshell, GitHub doesn't provide an oauth scope just for filing issues (c.f. https://github.com/dear-github/dear-github/issues/113). It's possible there are improved ways of handling this, lots has changed in the intervening years.

**Comment by miketaylr** [comment] 2019-11-05 22:00
(in the meantime, just file bugs anonymously -- no authorization needed)

**Comment by karlcow** [comment] 2020-01-03 08:13
Duplicate of #655

**Closed by karlcow** 2020-01-03 08:13 UTC

**Comment by annevk** [comment] 2020-01-03 08:19
So you don't plan on fixing this?

**Comment by karlcow** [comment] 2020-01-03 08:49
If we/when we have resources to fix it, it will be done with #655 
For now, you could report anonymously and leave your github handle in the form. 

The solution is to completely change the authorization model as mentioned in #655 
But right now we have a bigger fish to fry :) #3118 
https://twitter.com/webcompat/status/1212880610089299968

**Comment by annevk** [comment] 2020-01-03 09:19
But why have that issue as closed then?

**Comment by karlcow** [comment] 2020-01-05 23:31
@annevk I added the tag prio-backlog to #655. We have a lot of these of possible good ideas to do, but no time or resources to do it.
