### ISSUE TITLE
The text areas display a shadow

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#1611] opened 2017-06-22 08:19 UTC
**Environment:**
Browser / Version: Chrome 58.0.3029.110 (Desktop), Firefox 54.0.1 Release (Desktop)
Operating System: Windows 10

**Steps to Reproduce:**
1. Navigate to: https://webcompat.com/issues/new
2. Observe the text areas.

**Expected Behavior:**
The text areas have the same lineweight.

**Actual Behavior:**
The text areas display a shadow.

**Notes:**
1. Screenshot attached.

sv;
![screenshot](https://user-images.githubusercontent.com/16573771/27424107-999f881c-573c-11e7-8d96-bfd40b9ab0a5.jpg)

**Comment by magsout** [comment] 2017-06-22 08:30
Thanks @softvision-sergiulogigan 

Actually, this is a regression caused by https://github.com/webcompat/webcompat.com/commit/56d94cb996c160f1c4d27212d5f925ea89223924#diff-64589f250987f03e8530bc775a033edfR95.

The value of box shadow is wrong. it's not `.75` but `.075`.

**Comment by cch5ng** [comment] 2017-06-23 15:29
hi @magsout @softvision-sergiulogigan I can work on this as I'd been wondering about the change and was looking at the related CSS:

https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L198

https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/css/development/components/form.css#L107

**Comment by magsout** [comment] 2017-06-27 20:20
@cch5ng yes, cool!

**Comment by cch5ng** [comment] 2017-07-03 21:00
hi @softvision-sergiulogigan the fix for this was included in #1577 
so it should be ready to test/close. thanks.

**Comment by softvision-sergiulogigan** [comment] 2017-07-04 06:12
@cch5ng the shadows are still there, so we'll wait for the merge. Thank you for the heads up! I'll follow up on this issue in the coming days.

**Comment by cch5ng** [comment] 2017-07-05 17:12
@softvision-sergiulogigan thanks for your eyes. when you are doing your testing after the bug fix, are you just looking at webcompat.com typically?

also just a heads up that the shadow is not completely removed but the width has gone from 0.75 to 0.075 so it should be very subtle afterward. (affects the default input as well as the input with focus)

![screen shot 2017-07-05 at 10 04 15 am](https://user-images.githubusercontent.com/4755432/27876020-42338c80-616a-11e7-8e9d-e12f77bb5b04.png)

**Comment by softvision-sergiulogigan** [comment] 2017-07-06 07:11
@cch5ng 
> when you are doing your testing after the bug fix, are you just looking at webcompat.com typically?

If you are asking us if we test the fix exclusively on webcompat.com, and not on staging.webcompat.com or webcompat builds that are not yet released, the answer is YES.

**Comment by zoepage** [comment] 2017-07-06 23:31
I'd say, as the fix is merged, let's close this issue and re-open, if we need to. Thanks!

**Closed by zoepage** 2017-07-06 23:31 UTC
Labels: lang: CSS, status: good first bug, type: bug
