### ISSUE TITLE
needscontact needs to call the right API route.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#680] opened 2015-08-25 01:31 UTC
This is blocking #434 

The current call to needscontact is not carried on to the API call.

For example [needsdiagnosis](https://webcompat.com/issues?page=1&per_page=50&state=open&stage=needsdiagnosis&sort=created&direction=desc) is working well, but [needscontact](https://webcompat.com/issues?page=1&per_page=50&state=open&stage=needscontact&sort=created&direction=desc) is failing and being redirected to [all](https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc).

The call to the API was:   
`https://webcompat.com/api/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc` 
An API call is made to all, while when requesting sitewait for example the API  call is made to `https://webcompat.com/api/issues/category/sitewait?page=1&per_page=50&state=open&stage=sitewait&sort=created&direction=desc`

btw maybe an additional issue. In `https://webcompat.com/api/issues/category/sitewait?page=1&per_page=50&state=open&stage=sitewait&sort=created&direction=desc`

* `/api/issues/category/sitewait`
* `stage=sitewait`

seems to be redundant.

**Comment by miketaylr** [comment] 2015-08-26 21:00
Unrelated (maybe?) bug: If you visit [https://webcompat.com/api/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc](https://webcompat.com/api/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc) directly in the browser it's... surprising. :hankey: :point_left:

**Comment by karlcow** [comment] 2015-08-26 22:20
@miketaylr it's a JSON file. What did you notice was wrong?

**Comment by miketaylr** [comment] 2015-08-26 22:54
The bug is in `toggleFilter` of issue-list.js. Right now that will only do what we expect it to if there's a corresponding filter button with `[data-filter=needscontact]`, which I guess is kind of not great, but that means #434 will fix this.

**Comment by miketaylr** [comment] 2015-08-26 23:55
> @miketaylr it's a JSON file. What did you notice was wrong?

Oh, nevermind. >_< Not fully awake I guess.

**Comment by miketaylr** [comment] 2015-08-27 00:43
As for the issue about the redundancy, yeah that's a good point. Right now we just pass along all params to GitHub (and they don't seem to mind), but we could filter out our own at the API level.

**Comment by miketaylr** [comment] 2015-08-27 22:03
This will get fixed by https://github.com/webcompat/webcompat.com/pull/685. If somebody wants to refactor issue-list.js so it doesn't rely on certain DOM elements existing to succeed - that would be a cool contribution. Probably not a huge priority though. :bouquet:

**Comment by miketaylr** [comment] 2015-09-02 18:11
I'm gonna close this as a dupe of #434.

**Closed by miketaylr** 2015-09-02 18:11 UTC
Labels: bug, in progress, needs-test
