### ISSUE TITLE
Unable to use the same attach method 2 times in a row

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#1711] opened 2017-08-11 11:55 UTC
**Environment:**
Browser / Version: Chrome 60.0.3112.90 (Desktop), Firefox 54.0.1 Release (Desktop)
Operating System: Windows 10

**Steps to Reproduce:**
1. Navigate to: https://webcompat.com/issues/new
2. Attach a supported image (either Drag-and-drop or "Upload screenshot" link).
3. Remove the attached image.
4. Attach a supoorted image (the same method used at step 2).

**Expected Behavior:**
The image is attached.

**Actual Behavior:**
The image is not attached.

**Notes:**
1. Using the other method at step 4, attaches the image.

sv;

**Comment by zoepage** [comment] 2017-08-14 08:37
Can't reproduce. 🤔

@denschub would you also be able to check?

**Comment by softvision-sergiulogigan** [comment] 2017-08-14 08:45
@zoepage @denschub It seems I'm unable to reproduce it either on Firefox, but I can on Chrome...

**Comment by softvision-sergiulogigan** [comment] 2017-08-14 09:10
@zoepage both methods fail when they're not alternated.

**Comment by zoepage** [comment] 2017-08-14 09:15
@softvision-sergiulogigan please :)

**Comment by softvision-sergiulogigan** [comment] 2017-08-14 09:19
@zoepage this should do the trick...
![screen capture video](https://user-images.githubusercontent.com/16573771/29265744-d717ffda-80ea-11e7-973d-14754e66ed0f.gif)

**Comment by softvision-sergiulogigan** [comment] 2017-08-14 09:26
@zoepage On Chrome, at first DnD/click, I get this: "[Violation] Forced reflow while executing JavaScript took 32ms".
On Nightly, I get no message on DnD/click, and it works as expected.

**Comment by zoepage** [comment] 2017-08-14 09:31
Interesting. Thanks!

**Comment by zoepage** [comment] 2017-08-14 09:38
@softvision-sergiulogigan did you have the messages enabled?

**Comment by softvision-sergiulogigan** [comment] 2017-08-14 10:13
@zoepage These are the settings I used:
![o1gft4kvsikaznxx6pqfsq](https://user-images.githubusercontent.com/16573771/29267609-08d9ecf2-80f2-11e7-826f-8f7d1816ad68.png)

**Comment by miketaylr** [comment] 2017-08-15 20:05
I can reproduce. Investigating.

**Comment by miketaylr** [comment] 2017-08-15 20:23
It seems like Canary has stopped firing `change` events if you populate a file input with the same value.

That means `checkImageTypeValidity` won't get called (which ends up kicking off the preview junk, etc.):


`<input [type=file>.files` is [now settable](https://github.com/whatwg/html/commit/5dc7db2108656c9ce4b2dc7a8bb7dcde5c03afee), and according to http://wpt.fyi/html/semantics/forms/the-input-element/files.html, this works in Canary. That might be why their behavior changed?

I can cook up a fix for this.

**Comment by miketaylr** [comment] 2017-08-16 03:02
> That might be why their behavior changed?

Nope, unrelated. This is just how Chrome works: https://stackoverflow.com/questions/12030686/html-input-file-selection-event-not-firing-upon-selecting-the-same-file

**Closed** 2017-08-21 23:36 UTC
