### ISSUE TITLE
CODE_OF_CONDUCT.md isn't correct

### ISSUE THREAD

**Issue by Mozilla-GitHub-Standards** [webcompat/webcompat.com#2831] opened 2019-03-30 18:05 UTC
**Your required text does not appear to be correct**

As of January 1 2019, Mozilla requires that all GitHub projects include this [CODE_OF_CONDUCT.md](https://github.com/mozilla/repo-templates/blob/master/templates/CODE_OF_CONDUCT.md) file in the project root. The file has two parts:

1. Required Text - All text under the headings *Community Participation Guidelines and How to Report*, are required, and should not be altered.
2. Optional Text - The Project Specific Etiquette heading provides a space to speak more specifically about ways people can work effectively and inclusively together. Some examples of those can be found on the [Firefox Debugger](https://github.com/devtools-html/debugger.html/blob/master/CODE_OF_CONDUCT.md) project, and [Common Voice](https://github.com/mozilla/voice-web/blob/master/CODE_OF_CONDUCT.md). (The optional part is commented out in the [raw template file](https://raw.githubusercontent.com/mozilla/repo-templates/blob/master/templates/CODE_OF_CONDUCT.md), and will not be visible until you modify and uncomment that part.)

If you have any questions about this file, or Code of Conduct policies and procedures, please reach out to Mozilla-GitHub-Standards+CoC@mozilla.com.

_(Message COC003)_

**Comment by miketaylr** [comment] 2019-04-01 17:59
We can update this, though it's not technically a Mozilla project (just sponsored by Mozilla).

**Comment by hwine** [comment] 2019-04-02 04:09
Mike - no problem -- we worked off the [wiki](https://wiki.mozilla.org/GitHub] list.  I'll update that list to move ``webcompat`` to the "related projects" table.

**Comment by miketaylr** [comment] 2019-04-12 16:18
@hwine cool, we might merge the two, via #2840

**Comment by miketaylr** [comment] 2019-04-12 16:19
I'll close this as a dupe of #2840.

**Closed by miketaylr** 2019-04-12 16:19 UTC

**Comment by hwine** [comment] 2019-05-02 21:02
>  I'll update [that list](https://wiki.mozilla.org/GitHub#Are_there_other_unofficial_or_Mozilla-related_repositories_hosted_on_Github.3F) to move `webcompat` to the "related projects" table.

Done
