### ISSUE TITLE
Attaching another photo to an issue using “Drag and drop” should remove previous one

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#1571] opened 2017-05-29 14:48 UTC
**Steps to Reproduce:**
1. Navigate to: www.webcompat.com.   
2. Tap “Report bug” button.
3. Type in the required information and attach a screenshot.
4. After screenshot is attached, drag and drop another screenshot. 
5. Observe behavior.

**Expected Behavior:**
Screenshot is attached and previous one is removed.

**Actual Behavior:**
Screenshot is displayed and previous one remains attached.

**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

**Comment by zoepage** [comment] 2017-05-30 08:29
Thanks for the report @softvision-oana-arbuzov :)
This looks like inconsistent behavior we should tackle. 

Either there should be just one screenshot allowed. Then it needs to get replaced. 
Or there could be more than one, then they should all be displayed.
Not sure, if more than one are needed, are they @adamopenweb @karlcow @denschub?

**Comment by denschub** [comment] 2017-05-30 11:37
Most screenshots we receive are from the reporter extension anyway, and I've personally never found the need for more than one, so I'd vote for no. :)

**Comment by karlcow** [comment] 2017-05-31 08:27
yep for now I would just suggest we keep it for only one screenshot. Plus people can still had comments with additional screenshots.

**Comment by zoepage** [comment] 2017-05-31 09:22
Then I'd say its a bug. When a second screenshot is added, it should replace the previous one. 

Thanks @karlcow && @denschub for your feedback!

**Comment by karlcow** [comment] 2017-05-31 21:44
I had misunderstood the initial report. Yes this is a bug.  Thanks @zoepage

**Comment by karlcow** [comment] 2017-05-31 21:57
Ah! two possibilities for resolving this. 

* Either replace and add the new image at the next click on the area (interesting for me the drag and drop doesn't work for the second image). It replaces the window context with the full image. 
* Or deactivating the click as an attach event, given we have already the "remove image upload"

btw Maybe it should be "Remove uploaded image" (not sure).

@softvision-oana-arbuzov When you say " Screenshot is displayed and previous one remains attached." You mean the markup doesn't change but the image changes?

**Comment by softvision-oana-arbuzov** [comment] 2017-06-02 07:00
@karlcow The second screenshot is fully displayed on the screen. Dismissing it, on webcompat.com website the first screenshot is still attached and its link visible in "Give more details" text area.  
You can see the behavior on the attachment.

![secondimageopened](https://cloud.githubusercontent.com/assets/12184325/26714494/433ceb4e-477a-11e7-8795-a7ffa0045a45.gif)

**Comment by softvision-oana-arbuzov** [comment] 2017-06-02 07:09
Related to this issue, tapping the "Remove image upload" should remove the photo but also the link to it from "Give more details" text area.

**Comment by denschub** [comment] 2017-06-06 13:48
The cause of this is actually pretty simple: we use the file uploads `<label>` as a pseudo drag and drop implementation. Apparently, as soon as a file is assigned to the upload field, it stops accepting drop events, so Firefox opens the file as if you'd drop it anywhere else.

Possible workaround would be to listen to `drop` events and preventing the default here.

**Comment by cch5ng** [comment] 2017-06-06 21:36
hi, I think that this line is causing the issue:

https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L415

when the first image gets uploaded, an .is-hidden class gets added to one of the wrapper divs. but this also makes the #image input unavailable for further interaction. so I think instead of adding .is-hidden to the wrapper, it could just be added to hide the .wc-UploadForm-icon and .wc-UploadForm-label elements.

![screen shot 2017-06-06 at 2 15 23 pm](https://user-images.githubusercontent.com/4755432/26852998-1478d7b6-4ac5-11e7-95ac-edbc6ea0c62d.png)

this fixes the ability to replace the image. but some cleanup for the image link text is still needed in the description. (related to #1547 for form refactor)

**Comment by cch5ng** [comment] 2017-06-07 00:31
I will try to revisit the drop listener suggestion of @denschub again. 

I tried to implement a fix differently but got stuck a bit where if .wc-UploadForm-wrapper is not hidden, then after uploading an image, the button to remove the image is not interactive anymore and clicking that area only results in a file selection dialog to upload an image. but the other 2 items (replacing an uploaded image with one image; replacing old url strings) were fixed.

**Comment by cch5ng** [comment] 2017-06-08 19:01
@denschub hi, I can't find where the JavaScript logic is currently for the drag and drop behavior. should it be in bugform.js? https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js ... or could you point me to it?

I found an alternative way to change the functionality to how you suggest but it results in breaking other existing functionality that I would rather not do. would there be an acceptable alternative to catch the situation where one image was uploaded and if the user tries to drag/drop a second image, there would be a warning message that the first image should be removed using the button? thanks.

>  The cause of this is actually pretty simple: we use the file uploads <label> as a pseudo drag and drop implementation. Apparently, as soon as a file is assigned to the upload field, it stops accepting drop events, so Firefox opens the file as if you'd drop it anywhere else.

> Possible workaround would be to listen to drop events and preventing the default here.

**Comment by denschub** [comment] 2017-06-20 10:26
@cch5ng I am **very sorry** for not responding! I totally missed the notification and only found it when searching something else. 😿 

> I can't find where the JavaScript logic is currently for the drag and drop behavior. should it be in bugform.js? 

There is no JS logic at all! :) have a look at the HTML:

```html
<label class="wc-UploadForm wc-UploadForm--homePage js-image-upload-label" for="image">
  <div class="wc-UploadForm-wrapper">
    <div class="wc-UploadForm-icon" aria-hidden="true">
      <span class="wc-Icon wc-Icon--cloud-upload"></span>
    </div>
    <label class="wc-UploadForm-label">Attach a screenshot image</label>

    <input accept=".jpe,.jpg,.jpeg,.gif,.png,.bmp" class="wc-ButtonUpload" id="image" name="image" type="file">
  </div>
  <button class="wc-UploadForm-button is-hidden r-ResetButton" role="button" type="button" tabindex="-1">
    <img class="wc-Upload-Loader js-Upload-Loader" src="/img/upload-loader.svg" alt="Uploading image">
      Remove image upload
    </button>
</label>
```

That's actually a fancy .. workaround'ish solution that works in every browser: We want to have drag'n'drop support for `input#image`, which is a `type="file"` input. As it turns out, all browsers support dropping a file on the input field itself. In addition to the field, browsers also accept dropping a file onto the `input`s `label`. In our screenshot upload field, the entire "drop area" is actually inside the `<label>` tag, which basically creates a huge label for that field.

Dropping a file onto the `input` does basically the same as if the user has selected a file from the "pick file" dialog: the `onchange` event gets triggered. That's the place where we initiate the AJAX magic. I don't know where the defintion for that actually is, but you should be able to find it using the devtools:

<img width="719" alt="screen shot 2017-06-20 at 12 19 43" src="https://user-images.githubusercontent.com/344777/27328611-f6eab176-55b2-11e7-822e-0be571694a44.png">

(in your development instance, the source files won't be compressed, so the location actually will be useful)

I don't exactly know why it stops changing on a second drop. My initial thought was that we no longer drop on the label but on another element. That could be worked around by creating a new handler on whatever element we drop on, calling `preventDefault` and allowing the allow the drop to be bubbled up to the internal drop-handler for the label.

Note that the last paragraph is based on a assumption, I have not checked this at all. Feel free to ping if you need any help. :)

**Comment by denschub** [comment] 2017-06-20 10:42
Also, you probably already found a solution. Anyway. Sorry. ;)

**Comment by cch5ng** [comment] 2017-06-20 16:05
@denschub thanks for your responses.

I think there is a partial explanation for why the 2nd drag'n drop doesn't have the expected result:
https://github.com/webcompat/webcompat.com/issues/1571#issuecomment-306624657

also 
https://github.com/webcompat/webcompat.com/blob/1994276f0312b86a3df5c96efb83307d083d71a6/webcompat/static/css/development/components/upload-form.css#L42

no, I have not delivered a resolution but am working on it. it is not difficult to enable multiple drag and drops. but it is more challenging to refactor the existing logic to effectively handle the changed behavior request.

**Comment by cch5ng** [comment] 2017-06-22 16:44
coding on this issue should be pending delivery of #1306

**Closed** 2017-07-19 17:39 UTC
Labels: in progress, lang: JS, lang: Python, scope: form - upload, scope: form redesign, type: bug

**Comment by cch5ng** [comment] 2017-07-22 00:28
for future reference (if there is a latter resource for improvements to the current fix in place):

* https://github.com/webcompat/webcompat.com/wiki/Z-Intern-Drag-and-Drop-(dnd)-Notes
* https://github.com/webcompat/webcompat.com/pull/1670 (probably only the last commit is important)
