### ISSUE TITLE
Allow for people to close issues on GitHub

### ISSUE THREAD

**Issue by gvanwaelvelde** [webcompat/webcompat.com#881] opened 2015-12-19 11:33 UTC
On webcompat.com I can close any issue I want, but on GitHub I can only comment.
If I want to close an issue on GitHub, I have to go to webcompat.com and close it there, so webcompat-bot can close it on GitHub. This makes no sense. Why not allow me to close it directly on GitHub?

Thanks.

**Comment by miketaylr** [comment] 2015-12-19 22:06
> This makes no sense. Why not allow me to close it directly on GitHub?

Hi @gvanwaelvelde -- this is unfortunately a limitation to the way that GitHub works. In order to be able to close an issue, you need to be one of the repository owners. Since we want the project to scale beyond the handful of people listed as owners, we hack around this on webcompat.com by using a bot (webcompat-bot) as a proxy when you close an issue. 

Open for suggestions on how we can make this better, but until GitHub allows anyone to edit issues I'm not sure.

**Comment by gvanwaelvelde** [comment] 2015-12-19 22:49
Hello @miketaylr ,
I already suspected there was a technical reason for this odd way of doing things. Thank you for your quick reply.

**Comment by miketaylr** [comment] 2015-12-21 16:09
@gvanwaelvelde sorry it's kind of a pain. We do have an open issue to add a hyperlink from a GitHub issue to the corresponding webcompat issue, so it will at least be less annoying to hop from one to the other: #267

I'm gonna close this as a dupe of that -- thanks for filing!

**Comment by miketaylr** [comment] 2015-12-21 16:10
Actually, that should have been #741.

**Closed by miketaylr** 2015-12-21 16:09 UTC
