### ISSUE TITLE
Bugform - Steps to reproduce clarity

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat.com#1819] opened 2017-09-12 13:48 UTC
Some history:

- We decided to test a revised bug form while in Berlin, which was implemented
- The `How did you get there?` field was pre-populated with example steps to reproduce
- Over time we found that users weren't modifying the STR and just leaving the default steps
- The default steps were removed to clean up the redundant info in bug reports

Now we have the same `How did you get there?`  title for the field, but maybe it lacks context. Many of the responses we get in this field are "I clicked a link" or "twitter" or just blank.

Anyone have ideas how we could improve quality in this field?

**Comment by softvision-sergiulogigan** [comment] 2017-09-12 14:11
How about we change the "How did you get there?" string with "Please help us reproduce your issue" and (maybe?) pre-populate the text area with "Step 1: Navigate to <Site URL string>
Step 2:..."

**Comment by softvision-oana-arbuzov** [comment] 2017-09-12 14:25
Maybe a "Hint" message ("Describe what steps you made to get there") in the text area, which becomes hidden when user types something.

**Comment by zoepage** [comment] 2017-09-12 20:16
Just linking the following issues as we had this discussion already at some point.

https://github.com/webcompat/webcompat.com/issues/1646#issue-241425434
https://github.com/webcompat/webcompat.com/issues/1007

There was also the idea of adding the "placeholder" message per Javascript as `placeholder` actually did not work.

**Comment by adamopenweb** [comment] 2017-10-12 14:57
Maybe we can make a decision on this one? Doesn't have to be the best, right now we aren't getting good answers many times. A simple text change we could deploy immediately. 

How does everyone feel about this?
`What steps did you take before this problem occurred?`
with the placeholder:
`Please be as detailed as possible.`


<img width="400" alt="screen shot 2017-10-12 at 10 53 09 am" src="https://user-images.githubusercontent.com/6587558/31502785-05b10696-af3c-11e7-9925-b101dca8336b.png">

**Comment by miketaylr** [comment] 2017-10-12 16:53
+1 to @adamopenweb's suggestion.

@magsout could you send in a PR for this? We can just use `placeholder` in the textarea since it's so short.

We can have more discussions on how to improve later, right now it's pretty lame.

**Comment by adamopenweb** [comment] 2017-12-15 21:06
We want to continue this discussion @softvision-sergiulogigan

**Comment by softvision-sergiulogigan** [comment] 2017-12-18 10:20
As mentioned in my previous comment and in the live discussion we had in Austin, I think we should try to improve in the Steps to reproduce clarity.
My suggestion is  still 

> How about we change the "How did you get there?" string with "Please help us reproduce your issue" and (maybe?) pre-populate the text area with "Step 1: Navigate to ...
Step 2:..."
Or make the text area mandatory with 50 characters or more.

We could test this in a 1 month AB Testing session, and see which form yields the more valid STR.

**Comment by karlcow** [comment] 2019-07-31 07:56
I will close this issue. See the comment in https://github.com/webcompat/webcompat.com/issues/1007#issuecomment-516739851

**Closed by karlcow** 2019-07-31 07:56 UTC
Labels: scope: form design, status: discussion
