### ISSUE TITLE
all issues page: filters not reflected in URLs, can't link to filtered list

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#532] opened 2015-01-12 13:22 UTC
A #hash in the URL or something showing what filter is selected on the all issues page would let one link directly to a filtered list. Would be useful.

**Comment by karlcow** [comment] 2015-01-12 13:26
@hallvors this looks like a duplicate of #399
The hash sign (and not a good use of hashes) is not necessary once we have proper URLs.

**Comment by miketaylr** [comment] 2015-01-12 15:49
Yeah, this is supported in my #399 branch. Hope to have the bug finished by the end of the week (still a few complicated bits to solve).

**Closed by miketaylr** 2015-01-12 15:49 UTC

**Comment by miketaylr** [comment] 2015-01-12 16:27
I should note that the 5 filters (untriaged, needsdiagnosis) are currently linkable, e.g., https://webcompat.com/issues?untriaged=1. If you look at the "Browse Issues" part of the homepage the keys are hyperlinks to the filters.

But #399 will allow us to encode the rest of the filter state (num per page, direction, etc).
