### ISSUE TITLE
wrong milestone.json file gives an unhelpful message

### ISSUE THREAD

**Issue by Obtin** [webcompat/webcompat.com#2592] opened 2018-09-23 08:37 UTC
Edited by @karlcow (2018-09-25)

See my [comment](https://github.com/webcompat/webcompat.com/issues/2592#issuecomment-424170192) on how to improve this issue. I edited the title too.

Original report by @Obtin 
---
## Steps to reproduce
```
git clone git@github.com:<username>/webcompat.com.git
$ cd webcompat.com.git
$ virtualenv env
$ source env/bin/activate
$ pip2 install -r config/requirements.txt
$ npm install
$ npm run build
$ cp config/secrets.py.example config/secrets.py
```
After which  added the outh token and client id and secret key as per the documentation. After that,
```
$ npm start
```
This is what I got
```
sh: 1: source: not found
Writing logs to: /home/tina/webcompat.com/tmp
Statuses Initialization…
A milestone is missing or has been added: [u'worksforme', u'non-compat', u'needscontact', u'invalid', u'needstriage', u'duplicate', u'needsdiagnosis', u'sitewait', u'wontfix', u'fixed', u'incomplete', u'contactready']
Milestones are not initialized. Check logs.
```
## Reason
> Listed Milestones missing or extra in test-repo. 

But I checked there are no extra and the test-repo has all these milestones

**Comment by Obtin** [comment] 2018-09-23 08:38
This is my debug log file
![webcompat](https://user-images.githubusercontent.com/25207205/45925804-7affa880-beea-11e8-8f4e-75896e32aebd.png)

**Comment by karlcow** [comment] 2018-09-23 21:53
Thanks @Obtin

**Comment by karlcow** [comment] 2018-09-23 21:58
@Obtin When you are in the console, if you type `echo $SHELL`, what answer does it give?

**Comment by karlcow** [comment] 2018-09-23 22:05
This might still return the wrong information… hmmm…
`echo $BASH_VERSION`

**Comment by Obtin** [comment] 2018-09-23 22:15
@karlcow  The responses are 
```
echo $SHELL
/bin/bash
echo $BASH_VERSION
4.4.19(1)-release
```

**Comment by karlcow** [comment] 2018-09-24 00:36
Ok cool. You are using bash and not dash it seems. source doesn't exist it seems on dash.

**Comment by Obtin** [comment] 2018-09-24 04:10
@karlcow Yeah source does not for dash, but it should work bash. The output will give
``` 
$ ls -l `which sh`
/bin/sh -> bash
```
python run.py command gives 
```
Writing logs to: /home/tina/webcompat.com/tmp
Statuses Initialization…
A milestone is missing or has been added: [u'worksforme', u'non-compat', u'needscontact', u'invalid', u'needstriage', u'duplicate', u'needsdiagnosis', u'sitewait', u'wontfix', u'fixed', u'incomplete', u'contactready']
Milestones are not initialized. Check logs.
```
and the npm run start gives the same error as mentioned above

**Comment by karlcow** [comment] 2018-09-24 05:28
so I erased my milestones.json file in `data/` to be sure.
and ran `python run.py`
and it worked.

```
→ python run.py
Writing logs to: /Users/karl/code/webcompat.com/tmp
Statuses Initialization…
Oooops.
We can't find /Users/karl/code/webcompat.com/data/milestones.json
Double check that everything is configured properly
in config/secrets.py and try again. Good luck!

Fetching milestones from Github…
Milestones saved in data/
Milestones in memory
 * Serving Flask app "webcompat" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://localhost:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Writing logs to: /Users/karl/code/webcompat.com/tmp
Statuses Initialization…
Milestones in memory
 * Debugger is active!
 * Debugger PIN: 195-432-804
```

I checked your repo and you seem to have the right 12 milestones. 
Could you just erase data/milestones.json if it exists.

**Comment by Obtin** [comment] 2018-09-24 14:33
@karlcow It worked thanks :-)

**Comment by karlcow** [comment] 2018-09-25 00:40
Very cool. Now the issue is that there was a problem with `milestone.json` and it blocked the start of the project with an unhelpful message.  I'll change the title a bit.

**Comment by karlcow** [comment] 2018-09-25 00:43
For resolving this issue, we need:

1. Check if `milestone.json` has the right format.
2. If not, just go fetch a new set online and save it in `data/milestone.json`
3. (Maybe) creates a backup of the old one at least for debugging purpose.
4. Tell the user that we did (no surprises)

**Comment by marimeireles** [comment] 2018-10-10 20:39
@karlcow I didn't find the `milestone.json` file in my updated version of the repo. I believe that [this](https://github.com/webcompat/webcompat.com/blob/master/tests/fixtures/config/milestones_content.json) `milestones_content.json` is the equivalent.

If the json isn't in the right format I just have to make a new request to the person's private repo and get the same data again. Is that right?

If this issue is still relevant, could I take it?
Thanks!

**Comment by karlcow** [comment] 2018-10-11 00:39
@marimeireles After cloning a repo, the `milestones.json` (sorry for the typo above) is  never included locally. The file is created the first time, we run `python run.py` and it is saved in  `data/`. In the future, we need to find a better way to figure this out. 

All the things which are in `data/` are not saved or backup. This is on purpose.

The current process is here:
https://github.com/webcompat/webcompat.com/blob/2a4ea6b97c8fb96d251d9b9995c29c94dfa8a73a/config/__init__.py#L33-L72

**Comment by karlcow** [comment] 2018-10-11 00:42
@marimeireles to access this part:
 
> If this issue is still relevant, could I take it?
> Thanks!

You should make sure about this.
https://github.com/webcompat/webcompat.com/issues/2592#issuecomment-424169758

Basically create a bogus `milestones.json` inside `data/` and see if the program has an helpful message and/or action to solve the issue. 

And yes you can take it.

**Closed** 2018-10-19 05:13 UTC
Labels: lang: Python, prio: good next bug
