### ISSUE TITLE
When clicking on contribute it redirects to contributors

### ISSUE THREAD

**Issue by couci** [webcompat/webcompat.com#2161] opened 2018-02-19 14:33 UTC
When clicking on contribute it redirects to contributors
- that can be kind of misleading/confusing for people
- while checking which are the contributors is super cool (and can get people out of the confront zone) the call of action on "how to join" is not big enough

P.S @zoepage don't hate me too much, feel free to close this

**Comment by zoepage** [comment] 2018-02-19 21:44
Thank you very much for the report @couci. :)

Your report is a duplicate of https://github.com/webcompat/webcompat.com/issues/2088 and I've suggested options here: https://github.com/webcompat/webcompat.com/issues/2088#issuecomment-366663296 Wanna jump over to that issue and join on the discussion there? That would be great! :)

**Closed by zoepage** 2018-02-19 21:44 UTC
