### ISSUE TITLE
Get ML triage working again

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3212] opened 2020-02-19 18:02 UTC
It's unclear what this will involve, but us moving things around to accommodate the new workflow broke things.

https://webcompat-ml.readthedocs.io

**Comment by miketaylr** [comment] 2020-02-19 18:09
https://github.com/mozilla/webcompat-ml-deploy/blob/master/docker/needsdiagnosis/run.py#L89-L146 seems to be where some of the magic happens.

**Comment by miketaylr** [comment] 2020-02-19 18:10
Note the existing webhook is still receiving and responding to events: https://github.com/webcompat/web-bugs/settings/hooks/133615727

**Comment by miketaylr** [comment] 2020-02-21 02:59
@karlcow noticed in https://github.com/webcompat/web-bugs/issues/48695, it seems like the bot is working.

He proposes it should only do that once the `action-needsmoderation` label is removed.

**Comment by miketaylr** [comment] 2020-02-21 03:03
TODO for me: write down how and when we want this bot to do its job -- and how does that interact with #3144?

**Comment by miketaylr** [comment] 2020-02-24 20:43
> TODO for me: write down how and when we want this bot to do its job -- and how does that interact with #3144?

### Old model

Anonymous report -> needstriage milestone -> ML classifier runs -> Issue closed as invalid (possibly).

### Possible future models

We have a couple ways to handle this. The biggest constraint we face is not accidentally leaking content which may violate the terms of use (aka, abusive content). 

If we tell the bot to run on the private repo, before moderation happens we could do 2 things:

1. Classify the issues, and add labels, and not automatically close the issue. This will allow the moderator to close it as invalid after determining it's not abuse. 

However, that seems like wasted effort for an issue we know is invalid.

2. Classify the private issues, and close the invalid ones, but we create a new "closed as invalid" template for the public side of things.

We lose some information in the public space, but we don't waste time moderating or triaging issues that are garbage.

WDYT, @karlcow?

**Comment by softvision-sergiulogigan** [comment] 2020-02-25 08:57
> 2. Classify the private issues, and close the invalid ones, but we create a new "closed as invalid" template for the public side of things.

We think that this is the way to go forward.

However, we would like to come up with a suggestion:
If we could somehow manually trigger the ML bot to run on the Needstriage milestone, we could do this after each session of moderation. This way, everything bad remains in the private repo, and all the other accepted junk will be processed by the bot.

**Comment by karlcow** [comment] 2020-02-27 06:53
> @karlcow noticed in [webcompat/web-bugs#48695](https://github.com/webcompat/web-bugs/issues/48695), it seems like the bot is working.
> 
> He proposes it should only do that once the `action-needsmoderation` label is removed.

I think I understand why it worked for this one.
We have to think that everything is being done with delay.

The issue was created:

```
* 2020-02-24T09:00:34Z        webcompat-bot creates the issue
* 2020-02-24T09:00:35Z  +  1s webcompat-bot assigns browser-fixme
* 2020-02-24T09:07:22Z  +408s webcompat-bot changes the title to the original issue 
                              (means softvision team moderated it in the private repo)
* 2020-02-24T09:07:48Z  +434s oana closes the issue as invalid
* 2020-02-24T09:12:09Z  +695s webcompat-bot assigns the ML labels (about 12 minutes later)
                              tries to close it (already done by oana)
                              Assigns the milestone non-compat
```

A couple of things, here, 

* the ML classifier worked along oana in the same pocket of time of 12 minutes.
* Basically oana moderating the issue under 7min, the classifier bot had something to extract from the issue in the body and was able to work, aka to add data to what is happening. 

We need to have the classifier indeed to fetch the data only when the issue is being moderated.

One of the reasons for this is 
https://github.com/mozilla/webcompat-search/blob/bf82423f1017edd2d40d6b90146b2434c21c1d5d/webcompat_search/commands.py#L50-L68

It parses the body to get meaningful data.

## Issue: Conflicts/race in between human and bot.

When oana moderated the issue on the private repo, right away she went to the public one to be able to finish the analysis, aka before the bot itself did the work.  Their diagnostic was different.

let's check if this theory holds water.
https://github.com/webcompat/web-bugs/issues?q=label%3Aml-needsdiagnosis-false+is%3Aclosed

how much time in between creation and human moderation
* https://github.com/webcompat/web-bugs/issues/49088  < 6min
* https://github.com/webcompat/web-bugs/issues/49087  < 7min
* https://github.com/webcompat/web-bugs/issues/49076 < 3min
* https://github.com/webcompat/web-bugs/issues/48929 < 9min

ok. that seems to be consistent. When the bugs are not treated by the classifier bot, it's often that more than one hour passed in between creation and moderation.

**Comment by karlcow** [comment] 2020-02-27 07:29
> ### Possible future models
> 
> If we tell the bot to run on the private repo, before moderation happens we could do 2 things:
> 
>     1. Classify the issues, and add labels, and not automatically close the issue. This will allow the moderator to close it as invalid after determining it's not abuse.

I'm not sure, but i have the feeling that this would create issues wrt the way the data are handled in the models, it collects all events for an issue, and so here we introduce a divergent history (two timelines).

The issue i raised in the previous comment is really practical.

currently:

1. In the private repo, the humans are checking the bug report by loading the page in the right context, so this is work done. (acceptability check)
2. the human as soon as the moderation is done goes to the public repo to continue to analyze, understand the context of the issue (diagnosis validity check)

Acceptability and Diagnosis are two separate processus.

Proposal:

1. Private repo + Human: the person does acceptability check
2. public repo + Bot: The classifier will continue to run as planned on the public issue, but the trigger needs to be different (removing for example the `action-needsmoderation` as proposed before). the issue will be either closed or treated as valid.
3. public repo + human: the person does validity check on issues which have been not closed by classifier bot.

So it probably means to re-do work (as in reloading pages), you may expect that most of the work of the classification is done by the classifier bot. And only the good parts are kept for humans pre-diagnosis team.

**Comment by miketaylr** [comment] 2020-02-27 19:20
I think this makes sense, thanks @karlcow. Perhaps we need to re-think how we do the work, as you suggest: someone does moderation, and then we allow a period of "baking" time before triaging those same issues (to allow the bot to do its work).

**Comment by softvision-sergiulogigan** [comment] 2020-02-28 06:48
> Proposal:
> 
> 1. Private repo + Human: the person does acceptability check
> 2. public repo + Bot: The classifier will continue to run as planned on the public issue, but the trigger needs to be different (removing for example the `action-needsmoderation` as proposed before). the issue will be either closed or treated as valid.
> 3. public repo + human: the person does validity check on issues which have been not closed by classifier bot.

This sounds like a good plan!

> someone does moderation, and then we allow a period of "baking" time before triaging those same issues (to allow the bot to do its work).

This would not be an issue for us at all.

As we mentioned in the e-mail sent earlier this week, we performed a little test ourselves. We moderated everything (around 100 issues) on Sunday evening in hopes that by Monday morning (our time), the ML would run on the Needstriage list and close issues, but we noticed that it didn't.

I guess the fault is that we have not yet implemented the think Karl mentioned `The classifier will continue to run as planned on the public issue, but the trigger needs to be different (removing for example the `action-needsmoderation` as proposed before). the issue will be either closed or treated as valid.`

**Comment by karlcow** [comment] 2020-02-28 08:36
> https://github.com/mozilla/webcompat-ml-deploy/blob/master/docker/needsdiagnosis/run.py#L89-L146 seems to be where some of the magic happens.

While the labeling is happening in run.py.
The trigger is in the webhook. i opened
https://github.com/mozilla/webcompat-ml-deploy/issues/5

**Comment by karlcow** [comment] 2020-03-09 03:37
closing this here. followup in #3236

**Closed** 2020-03-09 03:37 UTC
Labels: lang: Python
