### ISSUE TITLE
Textarea progress bar hides text when typing

### ISSUE THREAD

**Issue by emilio** [webcompat/webcompat.com#3528] opened 2021-02-02 05:52 UTC
Happens on all browsers. It makes me not able to read what I'm writing for example. See screenshots.

![Screenshot_20210202-065150](https://user-images.githubusercontent.com/1323194/106557900-28efd880-6523-11eb-837e-c43e97fd3a70.png)

**Comment by softvision-oana-arbuzov** [comment] 2021-02-09 17:58
The issue is also reproducible on desktop layout.
![image](https://user-images.githubusercontent.com/12184325/107406522-2f78e400-6b11-11eb-9693-bac3ddadc529.png)

**Tested with:**
Browser / Version: Firefox Nightly 87.0a1 (2021-02-09)
Operating System: Windows 10 Pro

**Comment by karlcow** [comment] 2021-02-10 00:35
This can be easily fixed with 
```css
﻿﻿
/* webcompat.css | https://webcompat.com/dist/webcompat.css */

@media (min-width: 665px) {
  .issue-form .text-field {
    /* padding: 11px 36px 11px 8px; */
    padding: 11px 35px 3ch 8px;
  }
}
```

**Comment by karlcow** [comment] 2021-02-10 00:47
pull request done. https://github.com/webcompat/webcompat.com/pull/3534

**Comment by softvision-oana-arbuzov** [comment] 2021-02-17 10:03
@karlcow the issue is fixed on mobile but still occurs on desktop.

Mobile:
![image](https://user-images.githubusercontent.com/12184325/108188141-e7ad1a80-7117-11eb-8d05-9f0fd495fdc6.png)

Desktop:
![image](https://user-images.githubusercontent.com/12184325/108188198-f8f62700-7117-11eb-9e16-62a2de34c68b.png)

**Tested with:**
Browser / Version: Firefox Nightly 87.0a1 (2021-02-16)
Operating System: Windows 10 Pro

Reopening for further investigation.

**Closed** 2021-03-23 00:44 UTC
Labels: lang: CSS, type: bug
