### ISSUE TITLE
Cant use with webcompat addon on webcompat

### ISSUE THREAD

**Issue by jigarshah** [webcompat/webcompat.com#967] opened 2016-03-15 20:43 UTC
I see this issue every time on all sites. 

Install addon on fresh profile

go to webcompat.com

click on addon. 

Click on report via github (not logged in)

nothing happens. progress indicator is as it is. screen is disabled. 

![webcompat](https://cloud.githubusercontent.com/assets/214565/13793348/c6ee171a-eaf6-11e5-9981-b9b6e653742a.png)

FF config
Application Basics
------------------

Name: Firefox
Version: 45.0
Build ID: 20160303134406
Update Channel: release
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
Multiprocess Windows: 0/1 (default: false)
Safe Mode: false

Crash Reports for the Last 3 Days
---------------------------------

All Crash Reports (including 1 pending crash in the given time range)

Extensions
----------

Name: Firefox Hello Beta
Version: 0.1
Enabled: true
ID: loop@mozilla.org

Name: webcompat.com reporter
Version: 0.2.0
Enabled: true
ID: jid1-mjpB54bRzP9Zxw@jetpack

Name: WebEx Productivity Tools
Version: 2.0
Enabled: false
ID: ocplugin@webex.com

Graphics
--------

Adapter Description: Intel(R) HD Graphics Family
Adapter Drivers: igdumdim64 igd10iumd64 igd10iumd64 igdumdim32 igd10iumd32 igd10iumd32
Adapter RAM: Unknown
Asynchronous Pan/Zoom: none
Device ID: 0x0a16
Direct2D Enabled: true
DirectWrite Enabled: true (6.2.9200.17568)
Driver Date: 10-7-2013
Driver Version: 9.18.10.3324
GPU #2 Active: false
GPU Accelerated Windows: 1/1 Direct3D 11 (OMTC)
Subsys ID: 198f103c
Supports Hardware H264 Decoding: Yes
Vendor ID: 0x8086
WebGL Renderer: Google Inc. -- ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
windowLayerManagerRemote: true
AzureCanvasBackend: direct2d 1.1
AzureContentBackend: direct2d 1.1
AzureFallbackCanvasBackend: cairo
AzureSkiaAccelerated: 0

Important Modified Preferences
------------------------------

browser.cache.disk.capacity: 358400
browser.cache.disk.filesystem_reported: 1
browser.cache.disk.smart_size.first_run: false
browser.cache.frecency_experiment: 1
browser.download.importedFromSqlite: true
browser.places.smartBookmarksVersion: 7
browser.startup.homepage_override.buildID: 20160303134406
browser.startup.homepage_override.mstone: 45.0
dom.apps.reset-permissions: true
dom.mozApps.used: true
extensions.lastAppVersion: 45.0
gfx.crash-guard.d3d11layers.appVersion: 45.0
gfx.crash-guard.d3d11layers.deviceID: 0x0a16
gfx.crash-guard.d3d11layers.driverVersion: 9.18.10.3324
gfx.crash-guard.d3d11layers.feature-d2d: true
gfx.crash-guard.d3d11layers.feature-d3d11: true
gfx.crash-guard.status.d3d11layers: 2
gfx.crash-guard.status.d3d9video: 2
gfx.direct3d.last_used_feature_level_idx: 0
media.gmp-eme-adobe.abi: x86-msvc-x64
media.gmp-eme-adobe.lastUpdate: 1458074069
media.gmp-eme-adobe.version: 15
media.gmp-gmpopenh264.abi: x86-msvc-x64
media.gmp-gmpopenh264.lastUpdate: 1458074070
media.gmp-gmpopenh264.version: 1.5.3
media.gmp-manager.buildID: 20160303134406
media.gmp-manager.lastCheck: 1458074065
media.hardware-video-decoding.failed: false
network.predictor.cleaned-up: true
places.history.expiration.transient_current_max_pages: 64785
plugin.disable_full_page_plugin_for_types: application/pdf
privacy.sanitize.migrateFx3Prefs: true

Important Locked Preferences
----------------------------

network.cookie.prefsMigrated: true

JavaScript
----------

Incremental GC: true

Accessibility
-------------

Activated: false
Prevent Accessibility: 0

Library Versions
----------------

NSPR
Expected minimum version: 4.12
Version in use: 4.12

NSS
Expected minimum version: 3.21.1 Basic ECC
Version in use: 3.21.1 Basic ECC

NSSSMIME
Expected minimum version: 3.21.1 Basic ECC
Version in use: 3.21.1 Basic ECC

NSSSSL
Expected minimum version: 3.21.1 Basic ECC
Version in use: 3.21.1 Basic ECC

NSSUTIL
Expected minimum version: 3.21.1
Version in use: 3.21.1

Experimental Features
---------------------

**Comment by karlcow** [comment] 2016-03-16 01:36
@jigarshah Thanks for the very detailed bug report.

The issue is worse than this for me. The add-on is not working at all on Firefox Aurora and current Nightly. I wonder if it's then an issue to deal at https://github.com/webcompat/webcompat-reporter-extensions

@miketaylr

**Comment by miketaylr** [comment] 2016-03-24 15:19
Hmmm. Very strange, but thanks for the report @jigarshah.

So it looks like Fx 45 on Windows is half working and 47 and 48 are *not* working in OSX (I suspect e10s for that part). But yes, those would be bugs opened against the add-ons.

**Comment by karlcow** [comment] 2016-03-24 23:16
just to confirm @jigarshah I had the exact same issue a couple of days ago. Where I had to open a new window to report a bug. because it was stuck with the loading wheel.

**Comment by miketaylr** [comment] 2016-03-25 14:50
If anyone sees this again, can you check the console for JS errors?

**Comment by jigarshah** [comment] 2016-04-10 13:36
15:35:42.961 Blocked loading mixed active content "http://webcompat.com/login"1 /

**Comment by karlcow** [comment] 2016-04-11 02:26
@jigarshah Thanks.

oooops. ping @miketaylr 
https://github.com/webcompat/webcompat-reporter-extensions/commit/0b24129e858ea4c32f6f22811a4342afab8a4c5e#commitcomment-17042407

**Comment by miketaylr** [comment] 2016-04-12 00:51
Well that's a crappy bug. Probably just forgot to update that when we moved webcompat.com to https. :(

I'll take care of this in https://github.com/webcompat/webcompat-reporter-extensions/issues/16, and hopefully AMO won't take too long to update.

**Comment by miketaylr** [comment] 2016-05-17 20:33
Let's close this as a dupe of https://github.com/webcompat/webcompat-reporter-extensions/issues/20.

**Closed by miketaylr** 2016-05-17 20:33 UTC
Labels: bug
