### ISSUE TITLE
Label Editor tests failing

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1817] opened 2017-09-11 11:09 UTC
Looks like our master build is broken. 

https://travis-ci.org/webcompat/webcompat.com/builds/274134699#L1310

Probably the label editor test wasn't adjusted? 
Verified on local setup that tests are failing.

**Comment by MDTsai** [comment] 2017-09-11 14:08
The editor doesn't change in this month: https://github.com/webcompat/webcompat.com/blame/master/webcompat/static/js/lib/labels.js

**Comment by zoepage** [comment] 2017-09-11 14:46
The editor didn't, but the labels as far as I understood? Or am I missing something @MDTsai :)

**Comment by miketaylr** [comment] 2017-09-11 15:28
@zoepage can you link to the build that's failing directly? Right now that points to the latest test and the line numbers don't match up. Thanks!

**Comment by miketaylr** [comment] 2017-09-12 04:54
Ah yeah. Thanks for the updated link!

That's the same bug as #1809. We didn't break our tests, geckodriver had a bug in 55. I fixed that in #1776 on the milestones branch, so let's close this as a dupe of that (and hopefully get that merged this week).

**Closed by miketaylr** 2017-09-12 04:54 UTC
Labels: lang: JS, scope: testing, type: bug

**Comment by zoepage** [comment] 2017-09-12 07:56
Thanks for the headsup!
