### ISSUE TITLE
Revamp https://webcompat.com/contributors

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1149] opened 2016-08-01 16:30 UTC
I think the content can be improved, and likely the design as well.

@adamopenweb would you like to do a review of the content? I think your work on onboarding might give you some good insight here.

**Comment by miketaylr** [comment] 2016-08-01 16:30
(Also we should be able to link to each section individually....)

**Comment by adamopenweb** [comment] 2016-08-12 18:33
Oops just realized I didn't respond here, I'm on it though.

**Comment by adamopenweb** [comment] 2016-08-17 19:17
I think we need a better introduction to this and description. I would like to make small videos that compliment each section which should make the site seem more personal. Also for language, I think the introduction should be much less technical. The content on the page already is good at describing the process and most can be used again. 

Here's a rough draft of the introduction.

**Comment by adamopenweb** [comment] 2016-08-17 19:25
**Welcome aboard! You can make a real difference for others on the web.**

The web is for everyone to create, explore and discover. Every day people are building new websites while imagining new ways for others to consume content. ~~This is exciting for us because we love to understand how websites work.~~ There are many venues to browse the internet: on computers, phones, tablets, TV’s and more. People expect websites to work regardless of the device or browser they are using. Sometimes it can be challenging for website developers to make that happen with every possible combination. This challenge is what we are passionate about.  We want to make the web accessible to everyone regardless of the device or browser they choose. We need your help to make this a reality.

At Webcompat.com we strive to:

- Discover
    - Website issues in any browser.
- Understand
    - The problem with the website and how to correct it.
- Communicate
    - The problem and resolution to the right person at a company or website.
- Improve
    - Processes and tools to make the experience better for the community.

{{ Why you should contribute - ***Needs more work*** }}

**You can make a huge difference in less than 5 minutes. Anyone can get involved.**

- This is an open invitation to participate in the web compatibility effort.
- It’s OK to try and make mistakes, this is an opportunity to grow personally and professionally.
- Learn from web development and standards from a different perspective.
- It's challenging, engaging, fun and social.
- Make new contacts in the community and with companies all over the world.

**How to contribute**
There are many different ways to contribute and they can be grouped in to three categories:

**Web bugs**
- The easiest way to get started is to learn how to identify a web compatibility issue and file a bug report.
- When you’re looking for more of a challenge you can try triaging new bug reports.
- If you’re looking to flex your web development muscles you can try diagnosing verified issues.
- For those who like to search online you can find contacts at companies and websites.
- Another easy way to get started is to contact companies and websites.

**Developing webcompat.com and tools**
- Great design doesn’t come easy help to mold the identity of webcompat.com.
- Thousands of people use our website help them by writing code for webcompat.com.
- Communicating with regions across the world is difficult help with localization.
- If you’re into crawlers and automation help us build tools for automated testing.
- The community makes decisions together join us in the decision making process.

**Community building**
- Take what you’ve learned and share with others, use these slides as reference.
- Setup local community meet ups to talk about issues that affect your region.

**Comment by haseebgit** [comment] 2016-09-02 03:39
i think we should add about communications, like how to reach out individual team member or team, communication channels, weekly meetings, mailing list etc

**Comment by adamopenweb** [comment] 2016-09-02 16:00
That's a good point @haseebgit. Maybe we should expand the Contact page a bit and add something to the welcome section here.

Also a few links to keep in mind while working on this page:
https://github.com/webcompat/webcompat.com/wiki/Contributor-role:-Issue-Triager
https://github.com/webcompat/webcompat.com/wiki/Contributor-role:-UX---Design
https://github.com/webcompat/webcompat.com/wiki/Contributor-role:-Web-Opener

**Comment by shwetaseema72** [comment] 2016-10-17 03:36
i think the contributors link should also be on the top so that the more number of visitors can see it and contribute.

**Comment by zoepage** [comment] 2017-01-17 11:24
I love this thread. So many really good ideas already! :)

The Rust community is well known for a good on boarding of new contributors. The structure of their index is clear and you are able to find everything really quick. 
https://www.rust-lang.org/en-US/community.html

**Comment by lockettm** [comment] 2017-02-03 02:06
As @zoepage suggested, I drafted specific roles that outline the ways to contribute. It’s a high-level overview of each role with links to relevant documentation and resources.  I’m not sure if the tone of voice is friendly enough--I tried to keep it conversational but concise. Feel free to make any edits or suggestions. 

I also reworked an introduction, as I think the first half of Adam’s previous draft is well suited for the About page changes mentioned in #1296. However, I’m not sure--so let me know your thoughts.

---
**Join us!**
Learn new skills. Connect with others. Improve the Web. 

We believe everyone should be able to use the Web from whichever device or browser they choose. You can help us make this a reality. We welcome all kinds of contributions. Whether you want to code, design, write, or outreach we can use your help! 

Explore the different ways to get involved below and reach out to the community on our [IRC channel](https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#questions-or-problems) or the [public mailing list](https://lists.mozilla.org/listinfo/compatibility). We’re here if you have any questions or if you just want to say hi. 

**Bug Reporter** 
The easiest way to get started is to report bugs you find on the internet. Anyone can identify a web compatibility issue and [file a bug report](https://webcompat.com/). It’s the first step towards resolving an issue, as we can’t fix bugs if we don’t know they exist. 

**Issue Triager** 
Before we can find a fix we need to figure out why it’s broken. A simple way to help is to confirm a bug by seeing if you can [reproduce an issue](#). If you’re comfortable, you can then use developer tools to help [diagnose issues](#) by looking for errors in the console and explaining what needs to be fixed. 

**Web Opener** _[Perhaps a different title?]_
Once the community has an understanding of a bug and how to fix it, it’s time for [outreach](#). 
Search online to find contact information for sites and companies then send them a message explaining the issue. It’s a simple way to get involved and make new contacts with companies located all over the world.

**Community Builder**
You know all about Web compatibility issues and want to help spread the word. Speak or write about webcompat.com to share what you’ve learned with others. You can even [host a local community meetup](https://activate.mozilla.community/webcompat-sprint/) to talk about issues that affect your region.

**Site Contributor** 
See something on webcompat.com that could be improved? Suggest a change or a new feature by [filing an issue](https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#filing-an-issue).  

You can also contribute by:

- Writing code for an existing [webcompat.com issue](https://github.com/webcompat/webcompat.com/issues)
- Making a UI or UX [design contribution](https://github.com/webcompat/design) 
- Using your native language to help with localization 
- Helping build tools for automated testing

**Comment by miketaylr** [comment] 2017-02-03 18:40
Great work @lockettm, the content is such an improvement.
> Web Opener [Perhaps a different title?]
It's a funny term, but I think it works. I may or may not have had this as a real job title in the past. >_>

I think next steps are probably to start wire-framing and think about how to design this, and then build it. @lockettm do you have any ideas here? The giant click-to-reveal stuff with overly big screenshots isn't the most elegant. ^_^

**Comment by lockettm** [comment] 2017-02-06 19:13
@miketaylr Ahh okay, Web Opener works. 

Yeah, the current “how to” panels demonstrate the process well but I agree, it’s a bit clunky.  

We could reformat and add the content to tabs (similar to the mock-up below) as a sort of “quick start guide.” 

Or, thinking ahead, we could build out landing pages for each role?
  
![wc-contribute-tabs](https://cloud.githubusercontent.com/assets/4382193/22659280/ea98bfdc-ec51-11e6-8f43-13635c3053f8.jpg)

**Comment by miketaylr** [comment] 2017-02-06 19:30
I like the tabs idea, visually. I assume that would just turn into a vertical list for mobile.

**Comment by adamopenweb** [comment] 2017-02-06 19:41
I agree, the tabs look nice. Also, we don't have a high percentage of users on mobile currently.
<img width="1144" alt="ga-contributors" src="https://cloud.githubusercontent.com/assets/6587558/22663366/4bae8996-ec7a-11e6-9b6a-b1e5fd77b934.png">

**Comment by zoepage** [comment] 2017-02-06 20:00
@lockettm great work :) it looks so much cleaner.

**Comment by karlcow** [comment] 2017-02-06 23:57
Adding @magsout to the discussion for the implementation part of the design.

* The navigation list as tabs is implementable. The issue comes with the smaller screens layout. @miketaylr mentioned vertical list. Maybe with flexbox and reordering the boxes with smaller viewport. That would be an interesting thing to test.
* The description roles can be implemented as flexbox. Similar to what I did for the boxes of http://www.la-grange.net/

**Comment by lockettm** [comment] 2017-02-07 04:16
@miketaylr A vertical list for mobile or an adapted design like the one below--not sure how difficult it'd be to implement. 

http://codepen.io/hayatbiralem/pen/KpzjOL

<img width="301" alt="wc-contributor-mobile" src="https://cloud.githubusercontent.com/assets/4382193/22677285/4828c828-eca6-11e6-8437-46612569f369.png">

**Comment by karlcow** [comment] 2017-02-07 04:42
@lockettm from what I read these days, carousel and UX seem to no be friends. :) 
http://shouldiuseacarousel.com/

**Comment by lockettm** [comment] 2017-02-07 08:27
@karlcow Didn’t think of it as a traditional carousel i.e. it’s below the fold, not on the homepage, doesn’t look like an ad, no auto-rotating—which I agree can be frustrating. :)

That said, a list does have the benefit of displaying all of the descriptive titles—assuming the user scrolls beyond the expanded content.

**Comment by magsout** [comment] 2017-02-07 08:35
@karlcow  agree with @lockettm's Argumentation.

The website you mention is about big carousel on HOMEPAGE for marketing.

**Comment by magsout** [comment] 2017-02-07 08:41
@lockettm interesting idea. I like the layout. And the idea of tab is nice.

Your example for small screen is pretty good.

**Comment by denschub** [comment] 2017-02-07 10:22
> Or, thinking ahead, we could build out landing pages for each role?

The screenshot in https://github.com/webcompat/webcompat.com/issues/1149#issuecomment-277781858 looks worrying, the page is way too long to me, so I am definitely for splitting this up into at least two pages. Also, the "bottom" part of the contents look much nicer than the wall of text above.

However, aside from being picky, I don't have a solution for that available right now, but maybe that's something to think about.

**Comment by karlcow** [comment] 2017-02-07 13:30
ah good points everyone. Thanks @lockettm @magsout and @denschub 

I think I agree with @denschub too. URIs are cheap. We are not forced to put everything on the same page indeed. Lighter page given us space can indeed be nice too. :) It's not like people need to read a novel. We can even have more than two pages, specifically if we start to hide the content through tabs and navigation artifacts, we can as well, put them on different pages. :)

**Comment by zoepage** [comment] 2017-02-07 13:37
> URIs are cheap.

But clicks are not. ;) When we split up the content on different sites, this means an additional click. So we'd need a good directing concept first?

**Comment by karlcow** [comment] 2017-02-07 13:45
hmm I miss something. Are you talking about latency, or about actions. Because in the two cases, we will be clicking. change tab content, or change page. And for the latency I don't think it matters in this case given the content size.

**Comment by zoepage** [comment] 2017-02-07 13:51
@karlcow about action. open / close a tab on one site is different than leaving a site and moving to another.

**Comment by denschub** [comment] 2017-02-07 13:51
I highly doubt that a click is worse then getting a wall of text. :) But I agree we need to have a good plan of what we want to do before we do it. _(<-- most logical sentence ever)_

One idea would be to directly talk to the contributor on that page. I've seen a nice introduction into contributing to a project before, but I don't remember exactly where. Basically, there was a list of actions a contributor could help with:

> I want to…
>
> * …report a broken website.
> * …help build a community around web compatibility.
> * …help teaching web developers on how to avoid compatibility issues.
> * …help triaging, reproducing and adding more details to issues.
> * …dig deep into website sources and find issues.
> * …get in touch with site developers to resolve issues.

Where each item would link to the corresponding documentation with further details. *In theory*, we could even make something very interactive, asking questions like "Do you like talking to people?" or "Do you enjoy debugging issues deep inside source code snippets?". I remember we had something like this for mozilla in the past, but I don't remember the name that was put under.

**Comment by magsout** [comment] 2017-02-07 13:54
@karlcow 

>And for the latency I don't think it matters in this case given the content size.

Disagree, The latency in france is horrible on mobile network..

it's why actually is better to have one big size file than 4 small file 👎

**Comment by magsout** [comment] 2017-02-07 14:02
@karlcow 

>It's not like people need to read a novel. We can even have more than two pages, specifically if we start to hide the content through tabs and navigation artifacts, we can as well, put them on different pages. :)

Hum, we are talking about documentation and  motivation. 

When I read an article, I like this small component than display time to read the entire article. If it's > 5 minutes, I added it on read later. 

But for documentation It's different IMHO.
If you take the example of webpack, I agree. But If you look at the design of @lockettm , there is not a lot of reading. And I prefer to have everything on a page that on 5. 

We do not risk losing people if they click on 5 links?

**Comment by lockettm** [comment] 2017-02-07 20:50
Thanks for the great input everyone.

I should note, I’ll be testing redesign suggestions as mock-ups with users for feedback. So two design concepts with a range of ideas is an option for this first design iteration. Eg tabs vs separate pages (if there are no objections due to technical concerns).

I’ll take our collective assumptions and ideas to create additional variations to be tested.

**Comment by lockettm** [comment] 2017-03-07 01:18
Updating this discussion to add some insight gained from user testing.

Picking-up from a previous point, I vote for separate pages for the how-to guides. It didn’t seem to slow down users when they were asked to locate documentation.

<img width="687" alt="screen shot 2017-03-06 at 5 00 56 pm" src="https://cloud.githubusercontent.com/assets/4382193/23637110/87675074-028e-11e7-862b-bef7f7c8a955.png">

> Also, the "bottom" part of the contents look much nicer than the wall of text above.

<img width="551" alt="screen shot 2017-03-06 at 4 55 15 pm" src="https://cloud.githubusercontent.com/assets/4382193/23636977/b9222cac-028d-11e7-9465-7aee2090c733.png">

On the mockup, I added small icons to each role in hopes of visually breaking up the heaviness of the text (We'll need new icons if moving forward with this and #1374). However, one user still commented that it felt like too much text when they landed on the page. An option is to get rid of the double columns, with the goal of making it feel less overwhelming.

Also, some users were confused about contributing beyond the 3 part bug lifecycle. One fix may be to separate the roles into two separate sections. “Help Fix Bugs” and “Contribute to the Site/Community” for example.  
<img width="490" alt="screen shot 2017-03-06 at 4 58 08 pm" src="https://cloud.githubusercontent.com/assets/4382193/23637031/1ef87400-028e-11e7-914a-7c94df57c517.png">

**Comment by miketaylr** [comment] 2017-03-07 16:25
> I vote for separate pages for the how-to guides.

That's cool. It's also simpler to build.

**Comment by karlcow** [comment] 2017-03-08 02:25
separate pages are also better for linking.

**Comment by zoepage** [comment] 2017-03-09 14:18
For reference and context towards the icons:https://github.com/webcompat/webcompat.com/issues/1374#issuecomment-283363622

**Comment by karlcow** [comment] 2018-01-15 11:54
@lockettm do you have the texts from the mockups somewhere. So we do not have to type them again? Thanks :)

**Comment by zoepage** [comment] 2018-01-15 12:06
@karlcow We might not need the texts as #1933 is about new content, not the one above.

**Comment by zoepage** [comment] 2018-02-14 09:32
closing as this is in progress in #1933

**Closed by zoepage** 2018-02-14 09:32 UTC
Labels: scope: refactor, type: content
