### ISSUE TITLE
Wrong display of zooming

### ISSUE THREAD

**Issue by ioana-chiorean** [webcompat/webcompat.com#1225] opened 2016-11-07 22:28 UTC
1. I was looking at an issue
2. Fennec crashed
3. Restarted it from crash reporter
4. It was displayed in a column, stretched

Note 
- reload fixes it. 

<img src="https://cloud.githubusercontent.com/assets/1391451/20078667/3c2c0ba0-a54a-11e6-930d-cad90328e52b.jpg" width="300" height="550" />

**Comment by miketaylr** [comment] 2016-11-08 15:32
Yikes! I wonder how we can crash Fennec to investigate (or if this is just a fennec bug).

**Comment by magsout** [comment] 2016-12-10 13:20
Maybe a viewport bug with fennec because of crash? There is no special thing for zooming.

**Comment by adamopenweb** [comment] 2016-12-12 18:04
@magsout probably. Using request desktop mode makes it somewhat similar to this for me. I haven't been able to force fennec to crash, so I think we should close this issue for now. Unless someone can reproduce it.

Thanks for the report @ioana-chiorean!

**Closed by adamopenweb** 2016-12-12 18:04 UTC
