### ISSUE TITLE
"Type of bug" should allow multiple selections.

### ISSUE THREAD

**Issue by Obtin** [webcompat/webcompat.com#1992] opened 2017-12-31 16:36 UTC
Observed : 
- "Type of bug" allows selection of only 1 option.
- After choosing Something Else, no option to add a "Type of bug" other than the given options.

Expected:
-  The type of bug option offers you the facility to choose only one of the given types at a time. The case can also be encountered where the user has to report multiple issues about the same URL.
-   After clicking on 'Something Else' radio button, the user should be allowed to add 'The type of bug' he faced, since this option brief the bug.

Would you like to take this Bug?
Yes

**Comment by karlcow** [comment] 2018-01-01 09:23
> The type of bug option offers you the facility to choose only one of the given types at a time. The case can also be encountered where the user has to report multiple issues about the same URL.


We want one report for each type of issues. Not multiple issues in the same bug report. Because these might have different consequences and duplication for different issues on browsers bug trackers. Or different type of persons diagnosing the issue.

> After clicking on 'Something Else' radio button, the user should be allowed to add 'The type of bug' he faced, since this option brief the bug.

Somehow it's part of the "Please describe what was wrong". fwiw I think we should first analyze how these radio buttons have been used in the past to understand if it's worth keeping them around or improve them. 

So we don't shoot in the dark with another modification.

**Comment by karlcow** [comment] 2018-01-01 09:38
> So we don't shoot in the dark with another modification.

/me realizes this is missing context 👹 

This form has a long history of modifications and has been improved little by little. Initially there was a free field, which ended up with "This doesn't work" type of sentences. So it didn't help us to get a good sense of what was the issue. We proposed a limited set of the most common issues we had and evolved them (wording and type of issues) to help the people doing triage to understand what the issue is about. Most of the time very little information is communicated by the user. 

See 
* #31
* #432
* #619 kind of related.
* #1007 kind of related.
* #1828 

Hope it helps @Obtin This site starts to have a bit of history and development. 😅

**Comment by Obtin** [comment] 2018-01-01 15:44
@karlcow, I referred to all the bugs u mentioned. I totally agree that we have to consider many aspects for this. This indeed needs a lot of discussion in order to reach a better conclusion. After we reach a plan to work on. I would like to to work on this. Thank you.

**Comment by karlcow** [comment] 2018-01-04 05:00
@Obtin So there are two issues in the report here. So probably that would need to be separated.

1. Multiple bugs.  
   I don't think we want to encourage this. I let other people to chime in.
2. Something Else, no option to add a "Type of bug".  
   This is already handled partially by "Please describe what was wrong", which is a short summary of the issue. I proposed in #1828 that we use this for the title.

So instead of `www.example.com - see Bug description`, we inject `www.example.com - [the thing which was typed into what was wrong]`. It would create richer titles for our issues. 

If you look at the [issues list](https://github.com/webcompat/web-bugs/issues) it is very monotonous except for the ones created by @softvision-oana-arbuzov and @softvision-sergiulogigan They edit the titles by hands on GitHub.

That said the first step would be to extract all issues title and Description of what was wrong (since we started to do that, let's dig that info… with a blame.)

Ok it seems we started implementing the short summary/description in #1547 following the discussion in #1007 The #1578 pull request done by @cch5ng was merged by @miketaylr on June 30, 2017.

So we can check the issues reported after this date, even probably deployed a bit later. Let's try to find out. Changelog for #1578. Yup on July 2017, 7.
https://github.com/webcompat/webcompat.com/blob/master/CHANGELOG.md#530---2017-07-07

Let's go back to web-bugs. OK here we go with `is:issue created:>2017-07-07 sort:created-asc `
https://github.com/webcompat/web-bugs/issues?utf8=%E2%9C%93&q=is%3Aissue+created%3A%3E2017-07-07+sort%3Acreated-asc+

only 6 546 issues to review (instead of the 14647 and growing we have)

To not become crazy, probably we need to do a mass extraction (there are scripts to do github backup with each issues as JSON file.) and do distribution analysis and check if the description is more useful than the general type of issues.

**Comment by Obtin** [comment] 2018-01-04 07:29
> Something Else, no option to add a "Type of bug".
This is already handled partially by "Please describe what was wrong", which is a short summary of the issue. I proposed in #1828 that we use this for the title.

I agree this could be a solution.But don't we have to restrict the word limit then, since we want our title to be specific and brief and the description must provide all the information to the volunteers to understand the bug.Thus, I believe that 

> So instead of www.example.com - see Bug description, we inject www.example.com - [the thing which was typed into what was wrong]. It would create richer titles for our issues.

this won't be enough. We might need a brief of the issue too.
using something like this as u mentioned "https://codepen.io/epilande/pen/eZJGpP" could actually help mobile users more
I totally agree with this in #1007 

> Regarding Describe what was wrong? (versus Describe what behavior you see? and Describe what behavior you expect?) I could imagine that the quality regarding completeness sufficiency varies more due to the question being more open (referring to a diff between expected and actual behavior), but A/B could help to test this hypothesis.

> Regarding Did you test in another browser? = Yes, the user could optionally provide information about which browsers were tested with what result, e.g. lines (similar to Is this information correct?) that allow selecting a browser name, a version ("Current version", "Pre-release version", "Long-term-supported version") and a toggle button Works (green check mark) / Same issue (red cross).

**Comment by Obtin** [comment] 2018-01-04 08:33
> To not become crazy, probably we need to do a mass extraction (there are scripts to do github backup with each issues as JSON file.) and do distribution analysis and check if the description is more useful than the general type of issues.

r? @karlcow 
would this be fine?
https://github.com/tango-controls/GitHubBackup

**Comment by karlcow** [comment] 2018-01-04 08:45
about 

> But don't we have to restrict the word limit then, 

First learn from the data. What is the longest string, what is the shortest. Then discover if we need to limit.

> since we want our title to be specific and brief 

Yes and that's the case for description too.  See the screenshot below. 
For an example of informative and useful titles.
See https://github.com/webcompat/web-bugs/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Asoftvision-oana-arbuzov+
and https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+author%3Asoftvision-sergiulogigan

> and the description must provide all the information to the volunteers to understand the bug.

No. That is where the steps to reproduce information go. See the screenshot below.

<img width="354" alt="capture d ecran 2018-01-04 a 17 33 31" src="https://user-images.githubusercontent.com/505230/34555488-76d5bdb4-f175-11e7-95fd-3785cee70e23.png">

> this won't be enough. We might need a brief of the issue too.

see above.

**Comment by karlcow** [comment] 2018-01-04 08:48
About backuping tool 
> would this be fine?
> https://github.com/tango-controls/GitHubBackup

which ever you are comfortable with. I have used this one in the past. Be prepare to let it run for a while. It saves all the issues in their individual files. You will need a key from GitHub too. 

<img width="618" alt="capture d ecran 2018-01-04 a 17 47 02" src="https://user-images.githubusercontent.com/505230/34555881-677d035c-f177-11e7-883e-c625a79565cc.png">

https://github.com/josegonzalez/python-github-backup

**Comment by karlcow** [comment] 2018-01-09 02:34
Let's close this issue in favor of #1828

**Closed by karlcow** 2018-01-09 02:34 UTC
Labels: lang: HTML, scope: form redesign
