### ISSUE TITLE
Investigate issues being filed without milestones

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2920] opened 2019-09-07 00:04 UTC
It seems possible, though rare, for an issue to be filed with no milestone:

https://github.com/webcompat/web-bugs/issues?q=is%3Aopen+is%3Aissue+no%3Amilestone

The weirdest one (I haven't looked at all of them) is https://github.com/webcompat/web-bugs/issues/39408. History says webcompat-bot added the milestone, but it wasn't set until I manually set it.

![Screen Shot 2019-09-06 at 6 47 15 PM](https://user-images.githubusercontent.com/67283/64466721-1af11a80-d0d9-11e9-909d-6355b1ce3c30.png)

**Comment by miketaylr** [comment] 2019-09-07 00:04
In https://github.com/webcompat/web-bugs/issues/34387#event-2494836555, it looks like @haseebgit removed the milestone. 

@haseebgit was that intentional?

**Comment by haseebgit** [comment] 2019-09-07 16:01
@miketaylr Yes, Since issue was not confirmed and there was no diagnosis, I assumed for needscontact the issue has to legit and dignosis

**Comment by karlcow** [comment] 2019-09-08 23:34
for memory.
<img width="993" alt="Capture d’écran 2019-09-09 à 08 31 34" src="https://user-images.githubusercontent.com/505230/64496084-45f78c00-d2dc-11e9-88fc-54168c105144.png">

It's possible that some issues are being missed by the bot too, async process through http.

**Comment by karlcow** [comment] 2019-09-08 23:38
I have also noticed that most of them didn't have any labels. So probably indeed an issue with the server. I put all of them in needstriage.

**Comment by miketaylr** [comment] 2019-09-19 06:18
> @miketaylr Yes, Since issue was not confirmed and there was no diagnosis, I assumed for needscontact the issue has to be legit and diagnosis

@haseebgit ok. all issues must have a milestone, so if you remove it from one bucket, be sure to stick it in another.

**Comment by haseebgit** [comment] 2019-09-19 06:20
@miketaylr As far as I remember I did it for only one and i got caught :D

**Comment by karlcow** [comment] 2019-09-19 06:23
I think we should close it.

**Comment by karlcow** [comment] 2019-09-19 06:24
https://github.com/webcompat/web-bugs/issues?q=is%3Aopen+is%3Aissue+no%3Amilestone
0 open 0 closed.

**Closed by karlcow** 2019-09-19 06:24 UTC
