### ISSUE TITLE
"browser-firefox-mobile-nightly-59.0a1" label is hardly visible

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#1979] opened 2017-12-13 19:10 UTC
**URL**: www.webcompat.com
**Browser / Version**: Firefox Mobile Nightly 59.0a1 (2017-12-12), Chrome 63.0.3239.84 
**Operating System**: Windows 10 Pro
**Tested Another Browser**: Yes

**Problem type**: Design is broken
**Description**: "browser-firefox-mobile-nightly-59.0a1" label is hardly visible

**Steps to Reproduce**:
1. Navigate www.webcompat.com.
2. Type in the details of an issue and add the Firefox mobile browser version (e.g. Firefox Mobile Nightly 59.0a1 (2017-12-12)).
3. Log the issue and observe label.
  
**Expected Behavior:**
Label is visible.

**Actual Behavior:**
Label is hardly visible.

**Note:**
1. Issues example #14209.
2. Reproducible on Firefox 57.0 Release and Chrome 63.0.3239.84.
3. Screenshot attached.
4. This issue is related to #1971.

**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv

[![Screenshot Description](https://webcompat.com/uploads/2017/12/8996f754-5635-4f85-be03-873b15ccb55c-thumb.jpg)](https://webcompat.com/uploads/2017/12/8996f754-5635-4f85-be03-873b15ccb55c.jpg)

**Comment by miketaylr** [comment] 2017-12-13 23:33
Yeah, I think the default for "labels we set programatically" color is bad. We shouldn't have that label, but we can fix this bug.

**Comment by karlcow** [comment] 2017-12-13 23:42
This is a duplicate of both #1871 and #1258 and should be fixed by https://github.com/webcompat/design/issues/14

**Closed by karlcow** 2017-12-13 23:42 UTC
Labels: type: bug

**Comment by zoepage** [comment] 2017-12-14 23:30
Got fixed by https://github.com/webcompat/design/issues/100
