### ISSUE TITLE
Typing "label:type-media" doesn't work in the homepage search form

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1515] opened 2017-04-16 22:06 UTC
Noticed by @magsout 

Steps to reproduce.
1. Go the homepage
2. click/tap on the search icon
3. Enter `label:type-media`

Expected:
Get the list of bugs with `type-media` label

Actual:
Empty list with a URL being 
`https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=label%253Atype-media`

Note: `&q=label%253Atype-media`

Going to the issues list page and typing `label:type-media` in the search form is working and gives a URL
`https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=label%3Atype-media`

but if I take this URI and I cut and paste it in the browser, I get back the gibberish URI from the home page
`https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=label%253Atype-media` 
where the browser is trying to convert the percent into `%25`. So the progression goes indeed like this.

1. `label%3Atype-media`
2. `label%253Atype-media`
3. `label%25253Atype-media`

etc.

**Comment by miketaylr** [comment] 2017-04-17 17:50
Yeah, I feel like this is a dupe of some already existing issue... we screw up the URI encoding (probably in multiple places).

**Comment by magsout** [comment] 2017-04-18 09:56
@miketaylr @karlcow 

yeah, duplicate of https://github.com/webcompat/webcompat.com/issues/1345

**Closed** 2017-04-21 13:01 UTC
Labels: lang: JS, site-development, type: bug
