### ISSUE TITLE
Broken Pipe error in test environment

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#654] opened 2015-07-31 01:01 UTC
This is happening often in my test environ. I need to figure out why. 
Putting it here as a reminder 

```
127.0.0.1 - - [31/Jul/2015 09:56:49] "GET /api/issues/category/needsdiagnosis HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 49159)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
127.0.0.1 - - [31/Jul/2015 09:56:59] "GET /api/issues/category/contactready HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 49160)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
127.0.0.1 - - [31/Jul/2015 09:57:04] "GET /api/issues/category/new HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 49161)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
```

**Comment by miketaylr** [comment] 2015-07-31 02:23
I remember investigating this a while ago, but it looks like I didn't create an issue.

But basically it's a non-issue (IMO). It means there's some XHR request that hasn't completed and you've navigated away. You can reproduce in the dev server terminal by loading the homepage and going somewhere else really quickly.

See also http://stackoverflow.com/a/11866962
http://librelist.com/browser/flask/2012/1/18/broken-pipe/#b9ad6e1bf9108a89f0be791e17dde30e
etc.

**Comment by miketaylr** [comment] 2015-08-12 21:30
Going to close this, because it's not really related to this project. :hamburger:

**Closed by miketaylr** 2015-08-12 21:30 UTC

**Comment by karlcow** [comment] 2015-08-13 07:02
For archive, this is happening only we are requesting stuff to the /api/ route

```
→ egrep -B2 Exception broken-pipe.log | egrep '^127.0.0.1' | sed -E 's/^127.0.0.1 .*\] "//' | sed 's/HTTP\/1\.1" .*//' | sort | uniq -c | sort -nr
  53 GET /api/issues/100 
  23 GET /api/issues/category/sitewait 
  21 GET /api/issues/category/new 
  19 GET /api/issues/category/contactready 
  16 GET /api/issues/2 
  15 GET /api/issues/category/needsdiagnosis 
  13 POST /api/issues/2/labels 
  10 GET /api/issues/100/comments 
   5 GET /api/issues/category/mine 
   4 PATCH /api/issues/100/edit 
   4 GET /api/issues/category/closed?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc 
   2 GET /api/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=vladvlad 
   2 GET /api/issues?page=1&per_page=25&state=all&stage=all&sort=updated&direction=desc 
   2 GET /api/issues/search/new?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc 
   2 GET /api/issues/labels 
   2 GET /api/issues/category/sitewait?page=1&per_page=50&state=open&stage=closed&sort=created&direction=desc 
   2 GET /api/issues/category/contactready?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc 
   1 PATCH /api/issues/69/edit 
   1 GET /api/issues?page=1&per_page=25&state=open&stage=all&sort=created&direction=desc 
```
