### ISSUE TITLE
Can't upload image on iOS browsers

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2271] opened 2018-03-20 20:52 UTC
Originally filed: https://github.com/webcompat/web-bugs/issues/16102

`@ua_header: Mozilla/5.0 (Linux; Android 7.0) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/4.0.2 Chrome/65.0.3325.109 Mobile Safari/537.36`

**Comment by magsout** [comment] 2018-03-20 20:59
![d3603bb9-9c8c-4f71-9e25-2e1b2f5fda40](https://user-images.githubusercontent.com/1997108/37682407-c835b4b2-2c89-11e8-90f8-396a58661d41.png)
![a603eb5b-2dc6-4a81-9288-ce78da568540](https://user-images.githubusercontent.com/1997108/37682426-cfd69bb4-2c89-11e8-884e-98a600db98de.png)

@miketaylr I confirm, I’m able to reproduce.

**Comment by magsout** [comment] 2018-03-20 21:02
Same error with Firefox and Safari.

**Comment by magsout** [comment] 2018-03-20 21:04
Ah, I misread the title. Because I tried on iOS not Android. But I can’t upload any image on iOS

**Comment by miketaylr** [comment] 2018-03-20 22:11
> But I can’t upload any image on iOS

welp. Thanks.

**Comment by magsout** [comment] 2018-03-21 09:17
Same thing happened on Safari (Mac OS)
Firefox: ok
Chrome: OK

**Comment by magsout** [comment] 2018-03-21 10:52
I'm trying to figure out why

**Comment by magsout** [comment] 2018-03-21 17:54
Encore une chose, le bug arrive avec Safari (Mac OS), et tous les navigateurs sur iOS.

J'ai essayé beaucoup de choses avec ces navigateurs
- Télécharger une image fournie par mon téléphone: erreur
- Télécharger une image fournie par un autre appareil: erreur

J'ai essayé beaucoup de choses avec firefox (mac os):
- Télécharger une image fournie par mon iPhone: succès
- Télécharger une image fournie par mon mac: succes

**Comment by magsout** [comment] 2018-03-22 07:46
I was reading the comment of @karlcow https://github.com/webcompat/webcompat.com/issues/2276#issuecomment-375141425

I'm wondering, if the backend know anything about the browser sending the img?

**Comment by miketaylr** [comment] 2018-04-03 20:12
I wonder what kind of image iOS is sending...

That said, let's split out this bug for iOS and I'll file a new one for Focus Android. The file input doesn't even pop up there, so they seem like very different bugs.

**Comment by miketaylr** [comment] 2018-04-03 21:24
what on earth... where did the `d` go?

![screen shot 2018-04-03 at 4 24 11 pm](https://user-images.githubusercontent.com/67283/38276694-76d8ca50-375b-11e8-8e72-f5e2405c479d.png)


![screen shot 2018-04-03 at 4 23 52 pm](https://user-images.githubusercontent.com/67283/38276684-6e2313d4-375b-11e8-9997-c44fc6d72f9b.png)

**Comment by miketaylr** [comment] 2018-04-03 21:39
Desktop Firefox: 

![screen shot 2018-04-03 at 4 37 18 pm](https://user-images.githubusercontent.com/67283/38277233-50f08272-375d-11e8-92e2-da199a758002.png)


Desktop Safari:

![screen shot 2018-04-03 at 4 38 23 pm](https://user-images.githubusercontent.com/67283/38277267-72d70870-375d-11e8-8f47-f62f6635e87a.png)

Hm. Let's take a look at how we're creating this data URI.

**Comment by miketaylr** [comment] 2018-04-03 21:52
> Hm. Let's take a look at how we're creating this data URI.

Whoops.

`this.previewEl.get(0).style.backgroundImage.slice(5, -2)`

In Chrome and Firefox, `foo.style.backgroundImage` looks like: 

`"url("data:image/png;base64,iVBORw0KGgoAAA....kJggg==")"`

Safari looks like:

`"url(data:image/png;base64,VBORw0KGgoAAA...kJggg==)"`

pwned by assumptions in CSSOM serialization format.

**Comment by miketaylr** [comment] 2018-04-03 21:54
Probably we want to grab this data via regexp, seems safer.

**Comment by zoepage** [comment] 2018-04-09 09:38
This has been merged #2362 :)

Closing!

**Closed by zoepage** 2018-04-09 09:38 UTC
Labels: prio: important, type: bug
