### ISSUE TITLE
Image being downloaded on webcompat's pages

### ISSUE THREAD

**Issue by marimeireles** [webcompat/webcompat.com#2811] opened 2019-02-22 15:25 UTC
It's happening something similar to https://github.com/webcompat/webcompat.com/issues/2802 but this time I don't think it's related to fetching images from issues.

![screen shot 2019-02-22 at 12 18 01](https://user-images.githubusercontent.com/17600982/53251691-fcc35000-369b-11e9-90c8-b50f2b869bde.png)

It's happening only on the home page and only on Staging.

**Comment by marimeireles** [comment] 2019-02-22 15:29
Wait- I'm wrong. It's happening on webcompat.com and it is related to issues. It's downloading the images from the issues that shows in the home page. Probably the same kind of problem of #2802 .
I'll explore a little bit.

**Comment by miketaylr** [comment] 2019-02-22 16:25
Weird!

**Comment by miketaylr** [comment] 2019-02-22 21:25
@marimeireles do we have theories why this is happening yet? Just requesting an HTML-ish file should not request an image source... Does this happen because we put the HTML body inside a div, i.e., https://github.com/webcompat/webcompat.com/pull/2805? Can you checkout the revision before this landed and see if it reproduces?

**Comment by marimeireles** [comment] 2019-02-22 21:42
I think when we fetch issues using the [HTML function](https://developer.github.com/v3/media/#html) it returns the whole content of the issue, including the image.
So changing it to return only the [body](https://developer.github.com/v3/media/#raw) which returns raw+json like we used to should work.

**Closed** 2019-03-07 07:29 UTC
Labels: type: bug
