### ISSUE TITLE
Site hangs on bug submission

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat.com#986] opened 2016-03-29 17:44 UTC
STR:
1) Load broken website
2) Click Webcompat plugin site issue button
3) Fill in details about bug
4) Click Report via Github

Expected behavior:
Bug is filed, web is a better place for all.

Actual behavior:
Site hangs, spinner spins infinitely, reporter feels disappointed.

From console:
TypeError: Argument 1 of FormData.constructor does not implement interface HTMLFormElement.
BugForm/this.submitFormWithScreenshot()
 webcompat.min.js:6
r()
 webcompat.min.js:9
m.event.dispatch()
 webcompat.min.js:7
m.event.add/r.handle()
 webcompat.min.js:7
 webcompat.min.js

**Comment by miketaylr** [comment] 2016-03-29 17:57
Let's close as a dupe of #986.

**Closed by miketaylr** 2016-03-29 17:57 UTC

**Comment by miketaylr** [comment] 2016-03-29 19:08
```
[pid: 21556|app: 0|req: 9/9] 66.207.193.22 () {46 vars in 1071 bytes} [Tue Mar 29 19:04:00 2016] POST /issues/new => generated 5607 bytes in 405 msecs (HTTP/1.1 500) 2 headers in 100 bytes (2 switches on core 0)
```
