### ISSUE TITLE
Update Github queries to filter out type-media bugs

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat.com#1565] opened 2017-05-18 20:56 UTC
In the webcompat.com meeting on 5/18/2017 there was a discussion about filtering out type-media bugs from appearing on webcompat.com.

Recently a contributor was triaging a type-media bug that we normally don't focus on. We think we can prevent this from happening again by updating the Github queries to filter out type-media bugs.

Using `-label:type-media` seems to work on Github.

@karlcow @miketaylr do you see any issues with doing this?

This is related to #1356.

**Comment by karlcow** [comment] 2017-05-18 22:35
https://wiki.mozilla.org/Compatibility/Meetings/2017-05-18#type-media_.28miketaylr.29

```
type-media (miketaylr)

Where are we at, and what should our next steps be? Hide from UI?

    Adam: Karl has probably some feedback here. I'd think, we should hide it as contributors already jumped on them and wanted to triage them. Would it be easy to hide it?
    Tom: It should be when we hide them through webcompat.com.
    Adam: Is everyone okay with that?
    Tom: I think so.
    Adam: I don't think its the perfect solution, but a step forward.
    Tom: Probably also a lot of dupes. Shall we close all of them?
    Adam: The media team will probably want to take a look but yes.
    Guillaume: Is it possible to hide them from GitHub?
    Adam: https://github.com/webcompat/web-bugs/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20-label%3Atype-media%20label%3Astatus-needstriage%20
    Tom: We just add a minus sign in front of the label and it should be filtered out.
    Guillaume: I think, its easy to hide that label. --> Adam will file a follow up bug.
```

**Comment by karlcow** [comment] 2017-05-18 22:41
@wisniewskit About duplicates. See #1551 

@magsout we can't hide them from GitHub apart of yourself filtering them out doing `-label:type-media`

For the UI, we can indeed exclude them from the webcompat.com UI. That means we have to not forget about handling them on the github side. What I usually do

1. Go to needstriage and filter all issues related to `type-media`
2. Find the first one
3. Close the rest as duplicate of the first one. Repeat and Rinse.

Sometimes it takes one hour to do that. Sometimes less.

**Comment by karlcow** [comment] 2017-05-18 22:42
The ultimate question is when the media team will start handling those.

**Comment by karlcow** [comment] 2017-05-18 23:13
For example

* web.whatsapp.com https://github.com/webcompat/web-bugs/issues/5659
* (music|radio).yandex.com https://github.com/webcompat/web-bugs/issues/5628

**Comment by cch5ng** [comment] 2017-06-27 22:05
hi, I am starting to work on this issue. 
@karlcow in light of the earlier discussion about #1551 and how to handle the issues around type-media bugs, does this issue still require a fix?

otherwise, I think the solution requires updating this link:

https://github.com/webcompat/webcompat.com/blob/master/webcompat/templates/shared/shared-nav-links.html#L6

where href="{{ url_for('show_issues') }}?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc"
should become

href="{{ url_for('show_issues') }}?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=-label%3Atype-media"

afterward, I can verify that the corresponding api GET request looks like:

http://localhost:5000/api/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=-label%3Atype-media

2 effects: the negative filter for type-media only works if the user is logged into github. also the search input will be prefilled with "-label:type-media"

**Comment by karlcow** [comment] 2017-06-27 23:30
Let's hold on a little bit. a couple of days until we met Anthony Jones.

**Comment by cch5ng** [comment] 2017-07-06 22:23
although this is a back burner issue, I've been researching as it is interesting. new findings:

afaik only the github search api supports the negative filter (search x, not label type-media). the application currently retrieves issues using both the github issues api and search api. I do not think the issues api supports negative filters though.

* https://help.github.com/articles/searching-issues/#search-by-the-labels-on-an-issue
* https://developer.github.com/v3/issues/#list-issues-for-a-repository

this is the breakdown by view/route on which github api gets called:
* index.html => github issues api
* index.html (if search text entered) => github search api
* /issues (All Issues) => github issues api
* /issues (if search text entered) => github search api
* /activity => github issues api

in the code today, I think a small tweak like (below) could be done but it would only apply to issue lists coming from manual searches:
https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/issue-list.js#L188
could modify like: this.doSearch($.trim(searchValue) + '-label:type-media');
+ some conditional logic check if the user is logged in (otherwise there would be no results)

if you really want to have the negative filter for label then for the next gen app probably the issues retrieval should default to github search api (except I think there were notes about wanting to default more to the issues api because of rate limiting)

**Comment by miketaylr** [comment] 2018-03-23 14:36
I'm gonna close this, I don't think we'll have type-media in our future.

(we can revisit if we do)

**Closed by miketaylr** 2018-03-23 14:36 UTC
Labels: lang: JS, lang: Python, type: feature request
