### ISSUE TITLE
Think about ways to handle malware / spam reports

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2665] opened 2018-10-19 20:41 UTC
Sometimes we get reports that really belong somewhere like `https://safebrowsing.google.com/safebrowsing/report_phish/?tpl=mozilla&hl=en-US&url=https%3A%2F%2Fwww.google.com%2Fsearch`

Not sure if we want to expose that as an option to the user, or provide some tooling for us at triage time.

https://github.com/webcompat/web-bugs/issues/19992 is an example.

https://developers.google.com/safe-browsing/v4/lookup-api has a lookup API, but I don't see any submission APIs.

Just creating this report as a place to discuss ideas, or revisit one day.

**Comment by miketaylr** [comment] 2018-10-19 20:47
We always have the option to just close as INVALID, but reporting these to google is as easy as opening a URL, clicking I'm not a robot, and hitting submit.

**Comment by reinhart1010** [comment] 2018-10-27 10:00
#2214?

**Comment by karlcow** [comment] 2018-10-29 04:46
Duplicate of #2214 

Good call @reinhart1010

**Closed by karlcow** 2018-10-29 04:46 UTC
