### ISSUE TITLE
Unable to delete screenshot after dragging an invalid image type over it

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#3051] opened 2019-10-25 13:29 UTC
URL: https://staging.webcompat.com/issues/new 
Browser / Version: Firefox Nightly 71.0a1 (2019-10-24)
Operating System: Windows 10 Pro

**Steps to Reproduce:**
    1. Navigate to https://staging.webcompat.com/issues/new
    2. Fill in the requires information until reaching “Upload screenshot” area.
    3. Drag and drop a valid image file in the “Upload screenshot” area.
    4. Drag and drop an invalid image file in the “Upload screenshot” area.
    5. Try to delete/remove the screenshot.
       
**Expected Behavior:**
Case1: Image can’t be deleted/removed. “Delete this image” button is not available.
Case2: The valid image is removed after draging the imvalid image over.

**Actual Behavior:**
Image can’t be deleted/removed. “Delete this image” button is not available.

**Note**
    1. Screenshot attached.
    2. Also reproducible on Chrome 78.0.3904.70
	
Affected area:
```html
<div class="form-upload form-element js-image-upload js-Form-group">
	<input accept=".jpe,.jpg,.jpeg,.gif,.png,.bmp" class="form-input input-upload" id="image" name="image" type="file">
	<div class="shadow"></div>
	<div class="label-icon label-upload js-label-upload">
		<img class="add-screenshot-icon" src="/img/svg/icons/svg-add-image.svg" title="Upload screenshot" alt="Upload screenshot">
			<br>
				<small class="label-icon-message">Upload screenshot</small>
	</div>
	<div class="label-icon label-error is-hidden js-error-upload">
		<svg class="icon icon-big" role="presentation" title="An error occoured">
			<use class="icon-error" xlink:href="#svg-warning">An error occoured</use>
		</svg>
	</div>
</div>
```

![image](https://user-images.githubusercontent.com/12184325/67575162-9fa8fe00-f744-11e9-876f-00b98c0d5dc4.png)

**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov
@cipriansv

sv;

**Comment by miketaylr** [comment] 2019-10-25 16:32
This also reproduces in form v1, but the UI is slightly different ("delete this image" vs the little round X). We could fix this at the same time as https://github.com/webcompat/webcompat.com/issues/3049.

**Comment by miketaylr** [comment] 2019-11-06 23:12
@softvision-oana-arbuzov could you verify that this is fixed on production please?

**Comment by miketaylr** [comment] 2019-11-07 22:44
Actually, I just verified since I was testing something similar. This is working now.

**Closed by miketaylr** 2019-11-07 22:44 UTC
Labels: note: fix in both forms?, scope: new form QA, type: bug

**Comment by softvision-oana-arbuzov** [comment] 2019-11-14 14:45
Indeed the issue is fixed both on staging and production. The valid image is removed after dragging the invalid image over. Adding a new valid image, "Delete" button become available.

**Tested with:**
Browser / Version: Firefox Nightly 72.0a1 (2019-11-12), Chrome 78.0.3904.97
Operating System: Windows 10 Pro
