### ISSUE TITLE
Greatest hits radio select

### ISSUE THREAD

**Issue by calexity** [webcompat/webcompat.com#432] opened 2014-12-03 20:49 UTC
For bug reporting, populate a short list of most-submitted issues so it's easier to select what's going wrong.

As a mobile bug reporter
When I report a bug
Then I want it to be easier to select what's wrong
So I can report it faster.

**Comment by miketaylr** [comment] 2015-01-05 18:42
Looking at @magsout's commit, I wonder what about the case where the issue is "none of the above"? The current proposed design doesn't give an option for a user to write in their own summary. Would an option like "None of these, I'll write my own" that shows the "Problem in 5 words*" input be possible?

**Comment by calexity** [comment] 2015-01-11 04:49
@miketaylr @magsout I think that's fine, what about just moving "Add more details" up to right below this to make it more clear that they should just add it there?

**Comment by miketaylr** [comment] 2015-01-12 17:52
That could work @calexity. Would be cool to see a small mockup when you get a chance.

Would just need to come up with a nice generic bug title "bloop.com - [something generic here]"

**Comment by calexity** [comment] 2015-01-13 06:41
How about something like this?

Small
![largenewform - upload screenshot](https://cloud.githubusercontent.com/assets/1103366/5716908/12c4060a-9aac-11e4-87fc-6fee9839e097.png)

---
Large
![smallnewform - upload screenshot](https://cloud.githubusercontent.com/assets/1103366/5716909/12c73442-9aac-11e4-9140-a2d9147e5307.png)

For the bug title - maybe "bloop.com - something's wrong"

**Comment by miketaylr** [comment] 2015-01-13 16:51
Cool. I just realized "Don't know but something wrong" can probably be replaced entirely with "Other - I'll add details below."

**Comment by miketaylr** [comment] 2015-01-13 16:52
> "bloop.com - something's wrong"

That sounds good. Maybe we take the first few words from the description if it exists, and use that as a default.

**Comment by magsout** [comment] 2015-02-26 08:26
@miketaylr my PR it' ok with proposal from @calexity ? Just need to manage `form.py`to pupulate radio ?

**Comment by miketaylr** [comment] 2015-02-26 16:12
/o\, sorry for not looking at this for a while @magsout. I'll check out that PR either at some point today or tomorrow. It would be good to finish this feature soon to be able to tackle image uploading.

**Comment by miketaylr** [comment] 2015-02-28 00:46
OK, for people not following #524, I screwed up rebasing the branch and ended up closing the PR. Let me see if I can get this guy working and we'll pick it up from there.

**Comment by miketaylr** [comment] 2015-02-28 01:09
Here's what I see @magsout: ![](https://cldup.com/ZxLn-ZfVnM-2000x2000.png)

Looks good to me. So to finish the first parts of this bug (minus image upload etc.), there's two parts for me:

1) mess with the form.py stuff to add the "greatest hits" options. @karlcow - https://github.com/webcompat/webcompat.com/issues/432#issuecomment-66569321 looks like a reasonable place to start.
2) detect when to show the greatest hits version OR... do we just show this to everyone?

Looking at ![](https://cldup.com/TpyyHYeNSr-2000x2000.png) (this patch with a big viewport), I think we could just swap the position of the columns putting the inputs on the left and the radios on the right and then we wouldn't need to try any form factor detection.

3) make sure any changes in form stuff is properly reflected in our importer tool.

**Comment by miketaylr** [comment] 2015-03-04 22:43
Alright, let's start with these: 

* Desktop site instead of mobile site
* Mobile site is not usable
* Video doesn't work
* Layout is messed up
* Text not visible
* Other - I'll add details below

**Comment by miketaylr** [comment] 2015-03-04 22:46
Making a TODO list:

- [ ] add new `problem_choices` to form.py
- [ ] remove `owner_choices` from form.py
- [ ] remove `summary` input (this is being replaced by the choices, and users can still write a custom summary in the textarea)

**Comment by miketaylr** [comment] 2015-03-05 19:46
@calexity @karlcow @magsout should we make the radio select required, now that we're deriving the summary based on the users choice?

**Comment by miketaylr** [comment] 2015-03-05 22:42
OK, I think we should probably make the radio choices required so I went ahead and did that. I deployed everything so far to staging.webcompat.com if people wanna check it out. @magsout any CSS tweaks are most welcome. :smile:

**Comment by miketaylr** [comment] 2015-03-05 22:45
Oops, broke some tests. But I need to update tests for radio validation anyways.

**Comment by calexity** [comment] 2015-03-08 02:43
@miketaylr late to the party, but yes, I'd make it required.  All these fields are required. In fact, we could say that at the top or bottom "All fields are required so we can fix the problem."

**Comment by miketaylr** [comment] 2015-03-09 16:12
@calexity cool, I made it required.

**Closed** 2015-03-09 16:38 UTC
Labels: needs-definition, needs-design, site-development
