### ISSUE TITLE
"Site URL" field validation should be added

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#1742] opened 2017-09-01 09:17 UTC
**URL:** www.webcompat.com  
**Browser / Version:** Firefox Release 55.0.3 (Deskstop), Chrome 60.0.3112.113 (Desktop), Firefox Nightly 57.0a1 (2017-08-31) (Mobile)
**Operating System:** Windows 10 Pro, Huawei P10 (Android 7.0) - Resolution 1080 x 1920 pixels (~432 ppi pixel density)

**Steps to Reproduce:**
1. Navigate to www.webcompat.com.
2. Tap “Report bug” button.
3. On the “Site URL” field type an in invalid URL (e.g. test).
4. Observe behavior.  

**Expected Behavior:**
The invalid URL is not accepted. Error message is displayed (“A valid URL is required”)

**Actual Behavior:**
The invalid URL is accepted.

**Note**
1. Generic URI form ([link](https://en.wikipedia.org/wiki/URL)): scheme:[//[user[:password]@]host[:port]][/path][?query][#fragment]
 
**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv; 

![invalidurl](https://user-images.githubusercontent.com/12184325/29963433-820206fc-8f0f-11e7-8e15-78d2459332ae.png)

**Comment by karlcow** [comment] 2017-10-26 06:39
Duplicate of #1166

@softvision-oana-arbuzov This was closed in the past. We have routinely this discussion. The trade-off in between having real issues with invalid URL. 

I guess maybe the todo for this issue would be to compile all the URLs previously reported and see how much it is a problem. So we can base our decision on data.

**Comment by miketaylr** [comment] 2018-09-25 00:00
We require a valid URL now, so we can close here.

**Closed by miketaylr** 2018-09-25 00:00 UTC
Labels: lang: JS, lang: Python, scope: form redesign
