### ISSUE TITLE
Is there something better to do with "out of scope" bugs?

### ISSUE THREAD

**Issue by alex-mayorga** [webcompat/webcompat.com#1232] opened 2016-12-08 20:33 UTC
I believe that there are issues that are being closed that should remain open in the form of keeping them open and tag them "Not responsible site", "Not accessible site", "'App' only web service" or "Flash only site".

As a member of the community if the issue still exist it shall remain open not closed.

We could partner with blind accessibility organizations for example.

@karlcow asked me to file this and seems to have comments on this.

**Comment by karlcow** [comment] 2016-12-09 00:04
So we had a good discussion about this with @alex-mayorga 
There is a feeling that we are closing too quickly issues which are not in the strict scope of web compatibility (aka websites working differently in different browsers).  The issue goes along these lines:

* The Web is broken. Many sites do not have a mobile version, or are not accessible to people with disabilities, etc. etc. Every Web sites in the world is broken in a way.
* The Mozilla webcompat team (employees) are too few and can't handle the Web.
* Where do we draw the lines for keeping an issue opened? 
* Who will be doing the job of contacting the companies? Does it make sense to have thousand of open issues if we do not act on them?

## Example 
This to illustrate where it becomes very hard to address what constitutes a broken Web site and why we draw a line which is strict.

A web site doesn't provide a mobile Web site on any browsers. We ask them to fix it because some users are only on mobile. They fix it and provide a responsive Web site. The site adjusts now on small screens. We see that this new responsive Web site has poor performance over 3G. Do we ask them to fix the web site further? The site is provided only in English? Do we ask them to provide in other languages? How many languages are relevant?

The issue about fixing usability issues for the Web (which are important) is lot harder than trying to ask website owners to provide equivalent user experience on different browsers (which is already difficult).

Webcompat.com for example doesn't work in a terminal only browser such as lynx or w3m. Should we require webcompat.com to work on such a browser?

These usability issues are very important but their occurence is so large that it doesn't make sense anymore for us to address it. 

## In the search of a compromise.

Maybe there is a way where we could close these issues with a specific serie of labels depending on the type of problems they have.

**Comment by karlcow** [comment] 2017-01-13 02:14
from @miketaylr on the compat list
https://groups.google.com/d/msg/mozilla.compatibility/57LMFlg632E/ArXu2dvUEAAJ

>Rather than closing non-compat/interop issues as invalid, let's instead
> add a label to them (and filter them out from our valid
> dashboards/metrics/brains (if you prefer)).
> 
> They may be useful down the road, or for other groups, depending on how
> we label them.
> 
> Any objections? Or suggestions for what a label like that might look
> like? status-valid-bug-but-not-compat feels wordy. 

From this discussion there are two issues mixed in one:

1. what about issues which are not about different behavior in different browsers? (UX, readability, accessibility, flash, etc.)
2. what is the label we can associate with issues which is more informative to be able to filter them out for specific webcompat stuff.

Note that (1) is the recreation of (the old) [Tech Evangelism on Bugzilla](https://bugzilla.mozilla.org/buglist.cgi?product=Tech%20Evangelism&list_id=13392050) and that it feels a bit weird to address issues on the **webcompat** site which are not webcompat as we defined them initially.  For example, there are already plenty of [sites for Accessibility bug reporting](http://whoseline.a11yideas.com/bugs.html).

About (2), there has been a proposal for better labeling on the category of issues, but this is out of the realm of `status-*` it is a bit more something like `type-*` which is useful by itself. This is issue #1178

Then there is always the question of "who will cater for them?" if only for the triage, aka the number of issues related to lack of mobile site, bad UX, bad fonts, etc. exceeds tremendously the number of webcompat issues. It's a real question in terms of time dedication. All of that are not easy questions. And I perfectly understand @alex-mayorga point, but at the same time I have this little voice inside me.

**Comment by karlcow** [comment] 2017-01-13 02:14
I also wonder what @zoepage is thinking.

**Comment by miketaylr** [comment] 2017-01-13 10:52
> Then there is always the question of "who will cater for them?" if only for the triage, aka the number of issues related to lack of mobile site, bad UX, bad fonts, etc. exceeds tremendously the number of webcompat issues. 

No matter what, our team will have to triage incoming issues to find what we consider to be valid. After that... I'm not sure it matters. I would suggest we put them in a milestone for catchall/notcompat/tech evangelism/whatever. And Mozilla webcompat employees can feel free to ignore them, because it's totally not their mandate to worry about them. But there might be other people interested in working on them.

> It's a real question in terms of time dedication. All of that are not easy questions. And I perfectly understand @alex-mayorga point, but at the same time I have this little voice inside me.

I think it's OK to have a database for valid bug reports that have nothing to do with compatibility, even if the name of the site is webcompat.com. 

About to hop on a plane, if there's wifi I'll come back and give some more detail, if not, in a few days. ❤️

**Comment by adamopenweb** [comment] 2017-01-13 16:02
A few thoughts:

- For reports that fall into this category of invalid for web compat but are real issues, I think we should very clearly communicate the state of the bug, how others can be involved etc. To try to minimize confusion for the user.
- After a period of time, how do we know if the issue is still valid? Eg. site is flagged for not having a mobile site and goes responsive. 
- Running with something @miketaylr mentioned in IRC, we will catch more valid bugs by letting people report any website issues vs. forcing them to understanding what web compatibility means (to us) prior to reporting. I agree this is probably a better approach (for us) but I'm concerned that users will, over time, feel there is little value in reporting. I guess I'm ranting about managing expectations of users.

**Comment by karlcow** [comment] 2017-01-15 22:36
@adamopenweb 
> I agree this is probably a better approach (for us) but I'm concerned that users will, over time, feel there is little value in reporting.

That is one of my concerns. Tech Evangelism on Bugzilla, before I start a big clean up two years ago, had 10 years old bugs in the different language components. In the end it looked like something ala "it's where the bugs go to die".

**Comment by zoepage** [comment] 2017-01-19 10:09
> > I agree this is probably a better approach (for us) but I'm concerned that users will, over time, feel there is little value in reporting.

> That is one of my concerns. Tech Evangelism on Bugzilla, before I start a big clean up two years ago, had 10 years old bugs in the different language components. In the end it looked like something ala "it's where the bugs go to die".

I agree. This is why I feel we should still communicate very clearly what a web compat bug is and that we are taking care of **those**. This is our purpose. So we can manage the expectations of user in a better way. I'd pref to help with those and fulfill at least those expectations than none, because the scope is too big.

+1 on being able to report all bugs, so we don't miss any important ones. Is there a way to pass them on to another team that is responsible for bugs like this? So we could communicate very clearly a separation of concerns.

**Comment by karlcow** [comment] 2017-01-19 10:58
@zoepage 

>  Is there a way to pass them on to another team that is responsible for bugs like this?

not sure. the Scope of webcompat.com even if we have low participation from other browser vendors is to be totally cross-browsers. So there's no "team" 😆 per se. -moz-webcompat has a strong overlap with webcompat.com but not a complete overlap. It's why you do not see a lot of mozilla in the branding, so that it stays an open place for working together.

**Comment by zoepage** [comment] 2017-01-19 12:01
@karlcow 
> So there's no "team" 😆 per se.

Just to make it more clear, with `team`  I don't mean an existing team, but more like team / community / project... Just an entry point that we can point to. No matter if supported by mozilla or not :)

**Comment by miketaylr** [comment] 2017-01-19 16:01
> For reports that fall into this category of invalid for web compat but are real issues, I think we should very clearly communicate the state of the bug, how others can be involved etc. To try to minimize confusion for the user.

I agree. A boilerplate comment could be added at the same time that a bug is moved to a "tech evangelism/etc" milestone. And we should document in other places that this can happen

> After a period of time, how do we know if the issue is still valid? Eg. site is flagged for not having a mobile site and goes responsive.

We probably won't unless someone checks. We could do things like set up a process to flag a bug as "possibly-invalid" or old after 1 year, or get more aggressive and just close issues with a message (that seems a bit hardcore tho).

> Running with something @miketaylr mentioned in IRC, we will catch more valid bugs by letting people report any website issues vs. forcing them to understanding what web compatibility means (to us) prior to reporting. I agree this is probably a better approach (for us) but I'm concerned that users will, over time, feel there is little value in reporting. I guess I'm ranting about managing expectations of users.

I'm not sure closer users' (valid) bugs as invalid (compat bugs) will better for users expectations.

**Comment by miketaylr** [comment] 2017-01-19 16:07
@adamopenweb wrote:
> I agree this is probably a better approach (for us) but I'm concerned that users will, over time, feel there is little value in reporting.

@karlcow replied:
> > That is one of my concerns. Tech Evangelism on Bugzilla, before I start a big clean up two years ago, had 10 years old bugs in the different language components. In the end it looked like something ala "it's where the bugs go to die".

It totally feels like that some times, yes. But probably moreso because there were no active teams working on them for quite a while (but there have been individuals working on them sporadically).

On the other hand, if you look at any other product/component in Bugzilla, you will find bugs that are more than 10 years old, that are still considered valid and open. That's just the nature of collecting bugs in a large software project (Gecko or "the open web").

**Comment by miketaylr** [comment] 2017-01-19 16:12
@zoepage wrote:

> Is there a way to pass them on to another team that is responsible for bugs like this?

@karlcow replied:
>> not sure. the Scope of webcompat.com even if we have low participation from other browser vendors is to be totally cross-browsers. So there's no "team" 😆 per se. -moz-webcompat has a strong overlap with webcompat.com but not a complete overlap. It's why you do not see a lot of mozilla in the branding, so that it stays an open place for working together.

>> I think it is something important that we want to keep in mind. It is not a mozilla thing even if it is strongly made by mozilla.

There are other teams in Mozilla that are interested in certain issues, however. For example, there's a "flash kill" team that we could send a link to sites that still require flash to work (not a compat bug, but totally a bug if you don't have flash installed). There's also Tracking Protection bugs that get reported to us, and a team interested in that.

So yeah, not a Mozilla only project, but if the majority of bugs that come in are from Firefox, and are relevant to more than just our Mozilla compat team, I think it would be useful to involve other Mozilla teams. Moving them to an open component and labeling as certain categories makes this more possible than just closing them as invalid.

**Comment by miketaylr** [comment] 2017-01-19 16:25
OK, circling back to this after travel/weekends/holidays/work backlog:

1) We've wanted to have https://github.com/webcompat/webcompat.com/issues/132 for years. The motivation was to find a way to get site owners to be able to follow bug reports, and hopefully do something about those bugs. I think that pitch is much more compelling if it includes all kinds of bugs, not just web standards interop bugs, or the regular UA sniffing things. 

2) As mentioned above, there are other classes of valid bugs (that aren't the traditional "compat" bugs) that other teams in Mozilla would be interested in. 

3) I'm not too hung up on the name "webcompat.com". We have our own understanding of that term, but we have evidence that suggests when people talk about "compat issues" they just mean the site isn't working for them in their browser. Maybe it works in another, maybe not. These are still valid bugs and I think we should collect them. And then people who are getting paid to only look at Mozilla-related compat issues can put them in the other pile and ignore them. ^__^

...giving up on this numbering thing.

We don't know that keeping valid non-compat bugs will be a bad thing. It might be that some community could appear to take care of them, or it might be that they lay dormant forever, get labelled by a bot as "old", and... I think that's OK. It might be an opportunity for the bug reporter (if they're not anonymous, which most are) to engage with the site, if our boilerplate messages and docs are good enough. 

Personally, I think a diverse collection of valid bugs is way more interesting than a set of mostly invalid "not compat" bugs, as someone who is interested in the problem space of "websites not working".

**Comment by miketaylr** [comment] 2017-01-19 16:29
So in conclusion, my strawman proposal is to create a milestone called "Etc" and for valid bugs (a11y, UX, flash, tracking, broken everywhere), we stick labels on them, drop in a boilerplate message, and stick them in that milestone. I'll take on the work of finding teams interested in bugs that are relevant to them and deal with that.

Bikeshedding on the milestone name is welcome.

**Comment by zoepage** [comment] 2017-01-19 21:51
![Uploading Screen Shot 2017-01-10 at 11.14.31.png…]()

**Comment by karlcow** [comment] 2017-01-20 00:37
> So in conclusion, my strawman proposal is to create a milestone called "Etc" and for valid bugs (a11y, UX, flash, tracking, broken everywhere)

* So just for the record. I'm not comfortable with the proposal as-is. I think we are doing the mistake and reinventing Sumo and Mozilla Bugzilla. Not sure it is wise to do that. The reduced scope helps us to be effective and makes it a well defined purpose. 
* but we can try to improve the current process. 

If we go the way @miketaylr proposed, I would like:

1. First implement the status-milestones thingy. The **why?**: It will help us to simplify a lot the python and JavaScript code and to free part of it for handing labels as really categorizer, more than status management. It's a good thing.
2. To seek ways in the UI to better identify the type of issues. So we can focus our work where it matters for us as a Team.
3. To create bridges to more automatically transfer issues to Mozilla Bugzilla when these should be there (example Tracking Protection, SSL issues, etc.). **Rationale**: We should not force our system on other teams: "here is a big pile of bugs in our system, we don't want to deal with them, do whatever you want". We need to be more gracious. This could be a triage step, where with a special label, or actions help us to push an issue to bugzilla by cloning it and closing it locally and commenting automatically that this issue is now handled overthere. It might even be practical for other browser vendors.

Whatever we do, it will be a lot of work, and will take time.  Here trying to be realistic we what we can achieve.

**Comment by karlcow** [comment] 2017-01-20 00:43
> but we have evidence that suggests when people talk about "compat issues" they just mean the site isn't working for them in their browser.

We don't have evidences ;) We have indeed wrong reports it's not the same thing. Let's not forget the menu says: "Report Site issue". There's nothing related to webcompat into that and then when we reach the form, there is also no indication that they need to report a Web compatibility issue. :) I don't think it's because people don't understand webcompat, but more we are not talking about web compatibility at all during the process of reporting through the menu and forms. So it's a logical outcome.

It's why #1278 is a good and important suggestion if we figure out the right details.

**Comment by miketaylr** [comment] 2017-01-23 16:30
> If we go the way @miketaylr proposed, I would like:

These are all fine suggestions. None of them prevent us from putting valid-not-compat issues into a milestone today, and leaving them open.

**Comment by miketaylr** [comment] 2017-01-23 16:40
I just created the Milestone "non-compat" as a placeholder to stick issues until we resolve this issue. If we decide to close them all, we can do so all at once. Or if we decide to stick with that, we don't have to go back and look for bugs that fit the bill. 

<img width="1084" alt="screen shot 2017-01-23 at 10 38 37 am" src="https://cloud.githubusercontent.com/assets/67283/22213016/4ca1a77a-e158-11e6-9a35-9dea67366385.png">

(we should have the web fixed by 2032, I think, hence the due date).

**Comment by karlcow** [comment] 2017-02-15 05:27
How do we treat non-compat milestones into the UI.
Should we show the issues or not? Or provide an option so that someone can focus only on compat issues. To think. Probably needs to open a separate issue.

**Comment by zoepage** [comment] 2017-02-15 11:51
@karlcow As far as I understood, you talking about showing the issues on webcompat.com, right?

I feel like having an option to show them would be cool, but it should be off by default? We should keep the focus on webcompat-issues, I guess.

**Comment by karlcow** [comment] 2017-04-04 02:19
Let's close this issue. 
RESOLUTION: We created the milestone non-compat for handling them.
Any further issues about these non compat issues should be in a new issue.

**Closed by karlcow** 2017-04-04 02:19 UTC
Labels: scope: features, status: discussion, type: feature request

**Comment by miketaylr** [comment] 2017-09-05 02:28
> Any further issues about these non compat issues should be in a new issue.

Update: we decided to use this milestone as-is, but we will close all issues moving forward. Nobody really worked on them since April and there's no use is keeping these bugs around.

**Comment by adamopenweb** [comment] 2017-09-05 17:20
@miketaylr Sorry for not understanding this well enough. Does this mean we are still putting non-compat issues here? Should we have a time limit for these before closing?

Or do we now mark them as invalid again?

**Comment by miketaylr** [comment] 2017-09-06 05:19
@adamopenweb yeah, we still put them in non-compat. But close them at the same time. Is that right @karlcow?

**Comment by karlcow** [comment] 2017-09-06 08:38
@adamopenweb 
We put them in non-compat and close them automatically.
They are a bit different from invalid. Aka there is indeed a real issue, but it's not a valid issue with regards to webcompat.

invalid is an issue invalid in any contexts.
