### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat.com#1023] opened 2016-04-28 00:26 UTC
Looks like search is broken.
STR:
- Navigate to webcompat.com
- Click and type 'video'
- Click View All Open Issues and switch to View All Issues

Expected Results:
Display related bugs

Actual Results:
Error: "Not Found. Lost in Punk Cat Space"

Also navigating direct to this link doesn't work: https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=%22country%3A+jp%22

**Comment by hallvors** [comment] 2016-05-02 16:40
IMHO this is a side effect of #795 - the site does not allow you filter by various separate options right now. You can't both give a search word and a bug state, for example. The bugs #795 and #863 are about fixing that but my attempts so far were not solid enough.

(While I think it could be closed as a dup, I guess it will take time to fix those issues so we should perhaps add a workaround here)

**Comment by miketaylr** [comment] 2016-05-02 17:10
I don't think this is a dupe, this used to work.

**Comment by miketaylr** [comment] 2016-05-31 20:28
I think this bug is related, if not the cause:

0) from /issues, search for "country: jp". Note that it works and the URL is `https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=country%3A+jp`.
1) Try to navigate to `https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=country%3A+jp` (or just refresh).
2) Notice the URL is actually `https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=country%253A%2Bjp`

I think we're double encoding the URL here and the GitHub API is like wtf r u doing.

**Comment by miketaylr** [comment] 2016-05-31 23:00
I suspect that's happening here: https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/issue-list.js#L517
`jQuery.param` does `encodeURIComponent`: https://github.com/jquery/jquery/blob/df2051cf59d054d7ee91bdb554b583471942c6b4/src/serialize.js#L57-L90

So, original stuff works, but we are encoding already encoded junk and then it breaks.

**Comment by miketaylr** [comment] 2016-06-01 02:59
> I think this bug is related, if not the cause:

Nah, not the cause, just related to crappy search code. But might as well fix it in this branch.

**Comment by magsout** [comment] 2016-06-11 14:01
@miketaylr I writed a `SearchForm` Component with React, Redux, History, Form Serialized, Fetch ... Maybe it can be interesting you for webcompat

**Comment by magsout** [comment] 2017-04-26 08:02
althought https://github.com/webcompat/webcompat.com/pull/1518 is merged, still an issue. I can investigate if you want @miketaylr ?

**Comment by miketaylr** [comment] 2017-04-26 09:01
> althought #1518 is merged, still an issue. I can investigate if you want @miketaylr ?

Yes please!

**Comment by magsout** [comment] 2017-04-26 19:00
this link  https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=%22country%3A+jp%22 works now, it's fixed by #1518

**Comment by magsout** [comment] 2017-04-26 19:26
The error is reproducible only if we are not log in.

It would seem that this is a response from the local API

**Comment by magsout** [comment] 2017-04-28 20:02
Close due to https://github.com/webcompat/webcompat.com/pull/1531

**Closed by magsout** 2017-04-28 20:02 UTC
Labels: lang: JS, type: bug
