### ISSUE TITLE
Impossible to report a bug when an error is handle

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#2276] opened 2018-03-21 09:21 UTC
STR:
- go to staging
- filled out the form
- upload a bad img
- submit a form
- error message appears
- form is collapsed
- click on report a bug: nothing happened, form does not open

**Comment by magsout** [comment] 2018-03-21 09:37
![screen recording 2018-03-21 at 10 35 am](https://user-images.githubusercontent.com/1997108/37702721-bd0e7244-2cf3-11e8-972e-2cbb70e268d2.gif)

**Comment by zoepage** [comment] 2018-03-21 10:04
That's a good find! Added it to the P0 bug list...

**Comment by miketaylr** [comment] 2018-03-21 22:10
> upload a bad img

@magsout what are you using as a bad image?

**Comment by miketaylr** [comment] 2018-03-21 22:15
Ah, nevermind. I saved a text file as `foo.jpg` (you should be able to right-click and save, if anyone wants to):

![foo.jpg](https://user-images.githubusercontent.com/67283/37740351-65e6e41e-2d2b-11e8-937b-ebc4230a9e52.jpg)

**Comment by miketaylr** [comment] 2018-03-21 22:31
```
127.0.0.1 - - [21/Mar/2018 17:17:31] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/Mar/2018 17:17:44] "POST /upload/ HTTP/1.1" 415 -
```

Hmm.... when I try this with the same STR locally on the master branch, I still get a 415 (which is expected):

![screen shot 2018-03-21 at 5 21 13 pm](https://user-images.githubusercontent.com/67283/37740586-46b71e00-2d2c-11e8-8937-ad0cecaa1dae.png)

I wonder if #1655 is somehow related, given the same error appears? Or possibly has nothing to do with it.

Testing on master, the form isn't closed... so I guess this is a pretty bad regression.
![screen shot 2018-03-21 at 5 26 32 pm](https://user-images.githubusercontent.com/67283/37740800-0a6e8f86-2d2d-11e8-9cf3-5341ec97f9c1.png)

(same in Firefox).

@magsout can you tell me what kind of image you're testing with? This is a pretty bad bug, but it might be kind of an edge case that we can ship for a few days.

**Comment by miketaylr** [comment] 2018-03-21 22:35
I get the feeling this bug has been around since day 1 in terms of error handling... we've just made it worse.

**Comment by karlcow** [comment] 2018-03-22 00:41
@miketaylr so we are not in the case of the wrong filename extension, but in the case where the content is not an image and then not processable.

(Thinking out loud)

---

So the image is being sent to `/upload/` with a `HTTP POST` 

https://github.com/webcompat/webcompat.com/blob/master/webcompat/api/uploads.py#L124-L127

it reaches the `try` statement:

https://github.com/webcompat/webcompat.com/blob/master/webcompat/api/uploads.py#L141-L153

and sends a `415` to the **JS client** inside the page. 
---

What about having the JS client listening to 415 and have a JavaScript `reset_image_form()` function

1. resetting the values related to the image part of the form
2. Not collapse the form. 

(Probably naive)

**Comment by magsout** [comment] 2018-03-22 06:45
@karlcow 

there: https://user-images.githubusercontent.com/1997108/37755196-bb312e4c-2da4-11e8-8158-3eee1ae6b526.PNG

I use this image for my test, same for this issue https://github.com/webcompat/webcompat.com/issues/2271

it comes from my iPhone. But you can try with safari and every time you get an error :(

**Comment by magsout** [comment] 2018-03-22 06:46
@karlcow 

>What about having the JS client listening to 415 and have a JavaScript reset_image_form() function
    resetting the values related to the image part of the form
    Not collapse the form.


+1, in term of UX it's better than closing the form.

**Comment by Regaddi** [comment] 2018-03-22 16:08
This seems to be fixed with https://github.com/webcompat/webcompat.com/pull/2259.
The bad line of JS, which hides the entire form, when an error occurs on image upload, is removed with that PR.

https://github.com/webcompat/webcompat.com/blob/refactor/webcompat/static/js/lib/bugform.js#L553

**Comment by miketaylr** [comment] 2018-03-22 16:15
> This seems to be fixed with #2259.
> The bad line of JS, which hides the entire form, when an error occurs on image upload, is removed with that PR.

Ah, great find @Regaddi. So that didn't used to be a bad line, we just removed/changed what `loadingIndicator` is/was.

(it used to be an animated gif, now it's the form element itself:

```
<form
  action="/issues/new"
  class="form grid-row js-Loader loader"
```

**Comment by miketaylr** [comment] 2018-03-22 16:17
@karlcow wrote:
> What about having the JS client listening to 415 and have a JavaScript reset_image_form() function
> 
>     resetting the values related to the image part of the form
>     Not collapse the form.

Yes, I think we need something like this. 

> I get the feeling this bug has been around since day 1 in terms of error handling... we've just made it worse.

That's what I was hinting at... we don't have any graceful error handling for this kind of problem. I'll file a new bug, because it should be post-refactor follow up work.

**Comment by miketaylr** [comment] 2018-03-23 13:59
This should be fixed now. We'll do follow up work in #2288.

**Closed by miketaylr** 2018-03-23 13:59 UTC
Labels: prio: important, scope: refactor, type: bug
