### ISSUE TITLE
Consider accepting HTTPS connectivity submissions

### ISSUE THREAD

**Issue by jonathanKingston** [webcompat/webcompat.com#1342] opened 2017-02-16 03:54 UTC
Lots of sites suffer from inconsistencies in HTTP to HTTPS. I'm building an [extension](https://github.com/jonathanKingston/fix-my-http) to fix up HTTP connections however I wanted a way to auto detect errors on sites and also give users the option to report errors too.

This issue is to consider accepting reports for HTTPS issues.

Some examples of errors:
1.  Different content over HTTPS pages.(Struggling to find an example here however this is the main issue here and have seen them in building the extension)
    1. Different content served on purpose, Forbes used to do this. Seems super rare to intentionally have different content
    2. Server setup pages "OK it works", "Welcome to Apache", "Welcome to Nginx", "Phpinfo()"
    3. Poorly configured pages
2. Unsupported HTTPS (https://pitchfork.com/ https://labs.jensimmons.com/ https://schub.io/blog/2017/02/09/introducing-the-joy-of-diagnosis.html)
3. Timeout HTTPS pages(https://itv.com/)
4. Bad cert on HTTPS page with HTTP website redirecting to a valid HTTPS page (https://www.rubyjeansdiner.com/)
5. Valid HTTPS that redirects back to HTTP (https://www.stumbleupon.com/su/1fUFfI/:9Z5d14H+:aH$3iUGq/www.highexistence.com/life-secrets-and-tips?sms_ss=stumbleupon&at_xt=4d42de3bc63a2878,0/)
6. Mixed content issues, The extension actually fixes this by setting `upgrade-insecure-requests` however I could probably auto detect and report these for 'active mixed content' warnings that may cause page breakage (filtering out common tracking scripts etc).

Filing an issue at @miketaylr's request: https://twitter.com/miketaylr/status/832015110004736000

**Comment by miketaylr** [comment] 2017-02-16 18:42
My own personal feeling here is to accept these kinds of issues, with a `type-https` or `type-tls` label. 

Some (or all?) of these types of issues feel like "non-compat" Milestone issues -- the definition for that more or less means the issue reproduces in all browsers. 

@jonathanKingston Is there a community or group of people (Moz or otherwise) who would be willing to look after these kinds of issues and do outreach? Ideally we wouldn't be collecting issues to go stale.

**Comment by jonathanKingston** [comment] 2017-02-17 00:56
So I know @rlbmoz @marumari and :ulfr have been championing HTTPS adoption and outreach however I'm not sure if they would have the time.

Firstly we might benefit from a non US government resource like this https://https.cio.gov/everything/ to persuade website owners that HTTPs is worthwhile. This link is actually very good however it would be nice to be website agnostic as this is directed at US government website owners. Including talks like @estark37's  https://www.youtube.com/watch?v=iP75a1Y9saY from Chrome dev conference and other resources like the observatory and some of our advice we have on configuring TLS that April has worked on.

I'm not that familiar with how outreach happens (I notice the status-needscontact tag gets removed in Github so was struggling to find ones where sites have been contacted).

I found some past HTTPS issues and how they were handled:
- https://github.com/webcompat/web-bugs/issues/590 🍰
- https://github.com/webcompat/web-bugs/issues/127 ❌!!!!!
- https://github.com/webcompat/web-bugs/issues/126 ❌
- https://github.com/webcompat/web-bugs/issues/77 🍰🍰🍰
- https://github.com/webcompat/web-bugs/issues/549 ❌
- https://github.com/webcompat/web-bugs/issues/533 ❌
- https://github.com/webcompat/web-bugs/issues/439 🍰
- https://github.com/webcompat/web-bugs/issues/365 ❌
- https://github.com/webcompat/web-bugs/issues/294 ❌
- https://github.com/webcompat/web-bugs/issues/278 🍰 (now is ❌ again)
- https://github.com/webcompat/web-bugs/issues/166 🍰
- https://github.com/webcompat/web-bugs/issues/165 🍰 (mixed content warning though)

For me the highest priority is "Different content over HTTPS pages" issue as that is actually very hard to fix in something like HTTPS Everywhere or an extension like mine which is trying to be a lot more aggressive.

**Comment by jonathanKingston** [comment] 2017-02-17 01:18
The only non "non-compat" issues that I can think of are:
1. Cipher mismatch issues which we can probably direct the site authors to: https://mozilla.github.io/server-side-tls/ssl-config-generator/ and the documentation page: https://wiki.mozilla.org/Security/Server_Side_TLS
2. SSL version support

Another good security general advice link is: https://wiki.mozilla.org/Security/Guidelines/Web_Security#HTTPS

Format of reports:

1. Should there be different tags for each of the mentioned issues above?
2. Would screenshots of both HTTP and HTTPS differences be welcomed?
3. If there were a way to implement a "audit mode" to an extension where it recorded clicks for STR would that be useful?
4. If the reports are semi-automated, would +1's be useful for metrics?
5. Would testing for non public domains/ip addresses be useful?
6. Ask about software installed (enterprise gubbins/anti-viruses etc)

**Comment by karlcow** [comment] 2017-02-21 02:16
@jonathanKingston 

> 1. Should there be different tags for each of the mentioned issues above?

Do you need the granularity? If yes, then we could imagine `type-https-key` where the `key` is a subcategory.

> 2. Would screenshots of both HTTP and HTTPS differences be welcomed?

no specific opinion on this, except that most of the time, you get the site and you don't get the site. Recent example: https://github.com/webcompat/web-bugs/issues/4778

> 3. If there were a way to implement a "audit mode" to an extension where it recorded clicks for STR would that be useful?

No idea what you are talking about. 🤡 Probably because out of my comfort zone. Could you explain what it would be?

> 4. If the reports are semi-automated, would +1's be useful for metrics?

Not sure what you mean?

> 5. Would testing for non public domains/ip addresses be useful?

Explain :)

> 6. Ask about software installed (enterprise gubbins/anti-viruses etc)

So the more you ask questions, the longer the form, the more likely the person will give up the report. But indeed you could ask people if they are willing to give more information. 

About the issues which are Web compatibility issues. You are saying:

>    Cipher mismatch issues which we can probably direct the site authors to: https://mozilla.github.io/server-side-tls/ssl-config-generator/ and the documentation page: > https://wiki.mozilla.org/Security/Server_Side_TLS
>     SSL version support

First let's share what we consider as Web compatibility issues:

* development practices which lead a Web site to work in one browser and not in another. Such as using CSS prefixes for only one browser when the feature is implemented in other browsers. A JS method existent only in one browser. Basically the site is not working correctly in the browser of choice of the user. -> Contacting the Web site.
* Related to this first issue, we have two sub-cases: The used browser is having a bug (aka blink or gecko having something not working properly), or the browser has a missing feature or difference popular enough in other browsers that we need to implement it. -> Browser bug reporting.

What makes the two you are citing Web compatibility issues ?

**Comment by jonathanKingston** [comment] 2017-03-14 17:13
Hi @karlcow sorry for the delay.

The context for most of my comment was my own extension which is similar but more aggressive that HTTPS everywhere. I was also considering feeding in reports from server side checks too. So I was asking if submitting reports through a different source to this repo would be welcome and also if we could have the category as part of webcompat.com's extension also.

1. I think the granularity would help when it is automated (more information the better if it is reliable) however expecting users to pick the right ones from above might be a little too much. I was just thinking it might help filtering and addressing the highest priorities etc.
So for webcompat just a "https" category and other people can directly add specific labels like "https, https-redirect-issue"
2. External extension only
3. External extension only. Record clicks the user took to get to the broken page itself.
4. External extension only. If many users visited the same site, if the extension picked up the issue and found an existing report adding a +1 to the report on github rather than reporting more / doing nothing.
5. Intranet and local ip addresses might not be internet accessible to the wider web, sometimes we don't know when these sites even exist when upgrading protocols etc. If we can inform the user to report publicly we would know more about browser breakage ahead of time. Currently I suspect webcompat lets you report these just the same as if they were a normal site.
6. Agreed, maybe an expanding section of non required questions perhaps.

We are unlikely to catch browser bugs with these reports I suspect however a cipher mismatch to me would categorise itself as a issue which the website could be contacted with. The developer has not supported a cipher or tls version which breaks certain browsers etc.

Do you still allow reporting of "non compat" issues?

**Comment by karlcow** [comment] 2020-01-03 08:36
@jonathanKingston Doing winter cleaning. 

So the http issues are being handled a bit on a case by case. 
Specifically for TLS issues, we have label for these. 

But the rule of thumbs is that if the issue exists in all browsers (Safari, Chrome, Firefox) then we close it as non-compat. Note that non-compat doesn't mean it's not a real issue, but it's not part of our **webcompat workflow**. Think for example, of a website with non-valid markup, a website with accessibility issues for people with disabilities, very soon sites with Flash not working, etc. 

non-compat has been created for this specifically for people who wanted to contact sites. See #1232 for the rationale. Note that it would be possible to replicate the logic of webcompat.com and post these issues in their own repo.

**Closed by karlcow** 2020-01-03 08:36 UTC
Labels: status: discussion
