### ISSUE TITLE
Contextual menu entry for dictionary lookup in Mac Firefox

### ISSUE THREAD

**Issue by fixmacs** [webcompat/webcompat.com#3309] opened 2020-05-17 05:09 UTC
The Mac version of Firefox is missing the contextual menu item for dictionary lookup of a single highlighted word. One screenshot is from Firefox. The other screenshot is from Chrome. The Firefox right-click contextual menu option for "Look up..." is missing . 

![Screen Shot 2020-05-16 at 9 53 23 PM](https://user-images.githubusercontent.com/34322020/82136327-aae77800-97c1-11ea-8a13-c585fc1adade.jpg)
![Screen Shot 2020-05-16 at 9 54 19 PM](https://user-images.githubusercontent.com/34322020/82136328-ad49d200-97c1-11ea-97a0-b7856ef0c4ff.jpg)

**Comment by karlcow** [comment] 2020-05-18 01:11
This is not a webcompat.com issue. This bug tracker is dedicated to the development of webcompat.com server.

This also doesn't look like a website issue, it could be a browser UI difference which could be reported on https://bugzilla.mozilla.org/

Probably a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1116391

**Closed by karlcow** 2020-05-18 01:11 UTC
