### ISSUE TITLE
Investigate Status: "Error: no status for this issue" 

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#1980] opened 2017-12-13 19:29 UTC
**URL**: www.webcompat.com
**Browser / Version**: Firefox Mobile Nightly 59.0a1 (2017-12-12), Chrome 63.0.3239.84 
**Operating System**: Windows 10 Pro
**Tested Another Browser**: Yes

**Problem type**: Design is broken
**Description**: "browser-firefox-mobile-nightly-59.0a1" label is hardly visible

**Steps to Reproduce**:
1. Navigate www.webcompat.com.
2. Type in the details of an issue and add "Firefox Mobile Nightly 59.0a1 (2017-12-12), Chrome 63.0.3239.84" in the "Browser / Version" field.
3. Log the issue and observe the "Status" assigned.
  
**Expected Behavior:**
"Needtriage" status is displayed.

**Actual Behavior:**
"Error: no status for this issue" status is displayed.

**Note:**
1. Issues example https://webcompat.com/issues/14210.
2. Reproducible on Chrome 63.0.3239.84.
3. Screenshot attached.

**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv

![error_status](https://user-images.githubusercontent.com/12184325/33958287-963401fc-e009-11e7-83ca-36c9c2bf3851.png)

**Comment by karlcow** [comment] 2017-12-13 23:47
So I have a hunch why this is happening I just need to test and probably related to #1971

**Comment by karlcow** [comment] 2017-12-13 23:54
so interesting this string is parsed as by our current system. :) Because we didn't plan that people would put more than one browser there. 

`'browser-firefox-mobile-nightly-59.0a1-2017-12-12,-chrome'`

**Comment by karlcow** [comment] 2018-06-06 23:15
So… this one has been fixed by deploying #2471 
@softvision-oana-arbuzov feel free to reopen if you can reproduce your initial bug.

Thanks for reporting.

**Closed by karlcow** 2018-06-06 23:15 UTC
Labels: prio: important, scope: milestones, type: bug
