### ISSUE TITLE
`/` from `webcompat/webcompat-tests/issues` is encoded when trying to run local server on Windows

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#2497] opened 2018-06-18 09:00 UTC
**Environment:**
Operating System: Windows 10 Pro

**Steps to Reproduce**
1. Follow the information from [Development Environment setup](https://github.com/webcompat/webcompat.com/blob/master/docs/dev-env-setup.md#installing-virtualenv) guide.
2. Start local server http://localhost:5000/, using or `python run.py`.
3. Observe logs.

**Expected Behavior:**
`/` is not encoded in `webcompat/webcompat-tests/issues` link.

**Actual Behavior:**
`/` is encoded with `%5C` in `webcompat/webcompat-tests/issues` link.

**Note:**
1.  `secrets.py` file information:
```py
# Staging and Local instances use the same test repo
else:
    ISSUES_REPO_URI = os.environ.get('ISSUES_REPO_URI') or 'webcompat/webcompat-tests/issues'
```
2. Not reproducible on Linux Ubuntu 16.04.
3. Attached screenshot.
![encodding problem with the pathin secrets](https://user-images.githubusercontent.com/12184325/41526896-3854d412-72ee-11e8-9b22-e1a951e74731.png)

**Comment by miketaylr** [comment] 2018-06-18 19:16
Thanks @softvision-oana-arbuzov!

**Comment by miketaylr** [comment] 2018-06-18 21:30
Note: after getting the server running following the directions from https://github.com/webcompat/webcompat.com/pull/2503, I can't reproduce this.

@softvision-oana-arbuzov, will you test once you get the Ubuntu terminal running on your windows 10 machine?

**Comment by softvision-oana-arbuzov** [comment] 2018-06-19 14:59
@miketaylr , after installing Ubuntu terminal on Windows and making all the server configurations, I did not receive the error related to the `webcompat/webcompat-tests/issues` link and milestones were fetched.

**Comment by miketaylr** [comment] 2018-06-19 17:55
OK! Thanks! Let's close this then (aka, sweep it under the rug).

**Comment by softvision-oana-arbuzov** [comment] 2018-06-20 14:07
@miketaylr, I've investigated the issues and if I delete the "milestones.json" file from "Data" folder, I still receive the error, even if the encoding does not occur.
![image](https://user-images.githubusercontent.com/12184325/41663538-5ad96696-74ac-11e8-8013-de3d43031bbd.png)

**Comment by miketaylr** [comment] 2018-06-22 03:02
> I rather have the issues with the encoding fixed, than ask Windows users to use the Ubuntu terminal

I'd prefer to support and document a single path for windows users -- and using Ubuntu integration allows us to stick with unix-isms for build stuff. 

But also, I wasn't able to reproduce the error as reported. 😕

**Comment by softvision-oana-arbuzov** [comment] 2018-06-27 11:31
@miketaylr and @karlcow,


  for me it was still reproducible. 
One of my colleagues made some changes on the `__init__.py` and `secrets.py` files to be able fetch the `milestones.json` file and also to recognize paths on any platforms (using `os.path.join`).

`__init__.py`  changes:
```py
    milestones_content = None
    print('Statuses Initialization…')
    REPO_ROOT = ISSUES_REPO_URI.rpartition('/issues')[0]
    milestones_url_path = "/repos/" + REPO_ROOT + '/milestones'
    milestones_url = urlparse.urlunparse(
        ('https', 'api.github.com', milestones_url_path, '', '', ''))
    milestones_path = os.path.join(DATA_PATH, 'milestones.json')
```

`secrets.py` changes
```py
elif env.LOCALHOST:
    UPLOADS_DEFAULT_DEST = os.path.join(env.BASE_DIR, 'uploads')
    UPLOADS_DEFAULT_URL = 'http://localhost:5000/uploads/'


# Database backup path.
if env.LOCALHOST:
    BACKUP_DEFAULT_DEST = os.path.join(env.BASE_DIR, 'backups')
else:
    BACKUP_DEFAULT_DEST = ''
```

I'll attach my files here for review.
[ConfigFiles.zip](https://github.com/webcompat/webcompat.com/files/2140993/ConfigFiles.zip)

**Comment by karlcow** [comment] 2018-06-28 01:06
hmm in `__init__.py`, currently we already use `os.path.join()`

https://github.com/webcompat/webcompat.com/blob/a0dde5e397290e20e9cccf81533e64c25c0ed81c/config/__init__.py#L43

And that might be the source of the issue for @softvision-oana-arbuzov because 
* `REPO_ROOT = 'webcompat/webcompat-tests'`
* `milestones_url_path = 'repos\webcompat/webcompat-tests\milestones'` (on Windows)

Then once it goes into the urlunparse, it escapes the characters.
```python
>>> milestones_url_path = 'repos\webcompat/webcompat-tests\milestones'
>>> import urlparse
>>> urlparse.urlunparse(('https', 'api.github.com', milestones_url_path, '', '', ''))
'https://api.github.com/repos\\webcompat/webcompat-tests\\milestones'
>>> milestones_url_path = 'repos/webcompat/webcompat-tests/milestones'
>>> urlparse.urlunparse(('https', 'api.github.com', milestones_url_path, '', '', ''))
'https://api.github.com/repos/webcompat/webcompat-tests/milestones'
```
We can fix this just by using [`os.path.normcase`](https://docs.python.org/2/library/os.path.html#os.path.normcase):

```python
    milestones_url_path = os.path.normcase(
        os.path.join('repos', REPO_ROOT, 'milestones'))
```

```python
>>> milestones_url_path = 'repos\webcompat/webcompat-tests\milestones'
>>> import os.path
>>> os.path.normcase(milestones_url_path)
'repos/webcompat/webcompat-tests/milestones'
```

for the second change in `secrets.py`,  What does it fix? It seems unrelated. Let's focus on the first one.

**Closed** 2018-06-28 16:33 UTC
Labels: lang: Python, prio: important, type: bug

**Comment by softvision-oana-arbuzov** [comment] 2018-06-29 08:20
@karlcow the changes in `secrets.py` was to have the path recognized by any of the platforms.
