### ISSUE TITLE
Photo link remains displayed in “Give more details” text area when removing the uploaded image

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#1574] opened 2017-05-31 13:13 UTC
**Browser / Version:** Firefox 53.0.3 Release (Desktop), Chrome 58.0.3029.110 (Desktop), Firefox Nightly 55.0a1 (2017-05-31) (Mobile)
**Operating System:** Windows 10 Pro, Android 6.0.1

**Steps to Reproduce:**
1. Navigate to: www.webcompat.com.   
2. Tap “Report bug” button.
3. Type in the required information and attach a screenshot.
4. After screenshot is attached, tap “Remove image upload” button. 
5. Observe behavior.

**Expected Behavior:**
Screenshot is removed and link no longer available in “Give more details” text area.

**Actual Behavior:**
Screenshot is removed, but link to the screenshot remains displayed in “Give more details” text area.

**Note:**
1. Submitting the issue, will display all uploaded photos, regardless they were previously removed.

**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

**Notes:**
1. Screenshot attached.

sv; 

![screenshotlinknotremoved](https://cloud.githubusercontent.com/assets/12184325/26633473/2f98282e-461c-11e7-8163-736c5e612a51.gif)

**Comment by miketaylr** [comment] 2017-06-01 05:40
Yeah, this is a regression. Possibly a bug in the regex here:

https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L416-L437

**Comment by karlcow** [comment] 2017-06-01 05:46
Rha… my bad then. 
And it means we are missing a test for it. if we didn't detect it.

**Comment by karlcow** [comment] 2017-06-01 06:07
Yeah. My bad. Confirmed. https://github.com/webcompat/webcompat.com/commit/0d20e1189e067eecfdc99dc0b2156416a650e13f

This one is working.
`\[!\[[^\]]+\]\([^\)]+\)\]\([^\)]+\)$`

**Comment by zoepage** [comment] 2017-06-01 09:05
Thanks @karlcow :)

I'm sure, @cch5ng will be happy to add that test. (Also happy to help and walk you through.)

**Comment by cch5ng** [comment] 2017-06-01 21:45
hi, what should I do to simulate the fixed version? do I wait for a PR from @karlcow and then make a separate PR for the added test? thanks

**Comment by karlcow** [comment] 2017-06-01 23:51
@cch5ng as you wish. If you want to fix and add the test, I'm fine too. 
Or if you prefer me to do the PR request for the regex, I can do it too. 
Just tell me.

**Comment by cch5ng** [comment] 2017-06-02 00:37
@karlcow thanks, I can do both then (update regex and add a test).

**Comment by cch5ng** [comment] 2017-06-05 20:03
@zoepage I think this issue fix would be affected by #1547; this line would need to be updated

https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L429

because the old descField will be separated into 2 fields. is it better to make the fixes for this in #1547 or wait until that branch gets merged?

**Comment by zoepage** [comment] 2017-06-06 10:45
@cch5ng wait until #1547 is merged and then work on this. So we do things step by step. :)

**Closed** 2017-07-07 16:14 UTC
Labels: lang: JS, lang: Python, scope: form - upload, scope: form redesign, type: bug

**Comment by softvision-oana-arbuzov** [comment] 2017-07-10 07:10
I'm able to reproduce the issue on the new versions of Webcompat. The link is still displayed on "How did you get there?" text area, even if the screenshot was removed.

![photolinkremains](https://user-images.githubusercontent.com/12184325/28006399-cd45e9c6-6557-11e7-900f-52248ad044ed.png)

**Tested with:**
**Browser / Version:** Firefox 54.0.1 Release (Desktop), Chrome 59.0.3071.115 (Desktop), Firefox Nightly 56.0a1 (2017-07-07) (Mobile)
**Operating System:** Windows 10 Pro, Android 7.1.2
