### ISSUE TITLE
Missing label editor gear in Safari

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1694] opened 2017-08-01 18:15 UTC
In Safari 10.1.2, on OSX 10.11.6

1. be logged in
2. go to an issue

expected: can see label editor gear to edit labels
actual: it's hidden! if you click on where it should be, it opens as expected. weird.

<img width="1111" alt="screen shot 2017-08-01 at 1 12 14 pm" src="https://user-images.githubusercontent.com/67283/28840039-47ed7670-76bb-11e7-98f7-10eec80ef30b.png">

**Comment by brizental** [comment] 2017-08-01 20:15
So, I did some debugging on this, but I have no idea why it's happening. At first I thought it would be something simple, like this https://stackoverflow.com/questions/37155086/some-font-awesome-icon-not-rendering-in-safari and it makes sense, but  the solution did not work for us. Do you have any other ideas @miketaylr ?

**Comment by miketaylr** [comment] 2017-08-01 20:28
The only thing that immediately comes to mind is that the `aria-hidden=true` attribute there on the `<button>`. That shouldn't be there, right? Is it the same in other browsers? Might be a clue at something funky.

**Comment by brizental** [comment] 2017-08-02 01:25
@miketaylr oh yes. I tried changing that, no success. hahaha.

**Comment by zoepage** [comment] 2017-08-02 09:48
It's the same issue as with the icons above. All icons related to the icon font won't be displayed

**Comment by brizental** [comment] 2017-08-03 14:13
Duplicate of #1647

**Closed by brizental** 2017-08-03 14:13 UTC
Labels: type: bug
