### ISSUE TITLE
Some way to enlarge a screenshot that is not readable at column width

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#1017] opened 2016-04-24 05:58 UTC
See devtools screenshot in https://webcompat.com/issues/2483 - it would be nice if it enlarged on hover or click..

**Comment by miketaylr** [comment] 2016-04-25 13:51
This feels related to #722 -- embed smaller images by default, and then give the ability to see the larger images.

**Comment by karlcow** [comment] 2016-04-26 06:00
Yup it's the plan and on my todo list. Now that the other one is merged.
And I'm having already the pseudo code for this.

**Comment by karlcow** [comment] 2016-04-26 06:01
Closing as a duplicate of #722

**Closed by karlcow** 2016-04-26 06:01 UTC
Labels: good-next-patch
