### ISSUE TITLE
The “X Remove screenshot” text is black instead of yellow

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2540] opened 2018-07-03 13:44 UTC
**Environment:**
Browser / Version: Chrome 67 (Desktop), Firefox Nightly 63.0a1 (Desktop)
Operating System: Windows 10

**Prerequisites**
1. Webcompat Reporter add-on must be installed.

**Steps to Reproduce**
1. Navigate to any site (e.g. https://www.reddit.com/).
2. Click on the “Report Site Issue” icon from the top right corner.
3. Observe the “Screenshot” area.

**Expected Behavior:**
The “X Remove screenshot” text is yellow.
 
**Actual Behavior:**
The “X Remove screenshot” text is black.

**Note:**
1. Reproducible also when a file is drag and dropped.
2. Reproducible no matter the website accessed.
3. Reproducible also on Chrome 67.0.3396.99.
4. Not reproducible if the file is removed and replaced with another file using "Upload screenshot".
5. Screenshot attached.

**Affected area**
```html
<svg class="icon icon-big" role="presentation" title="Remove Screenshot">
	<use class="icon-remove" xlink:href="#svg-x">Remove Screenshot</use>
</svg>
<small class="label-icon-message">Remove screenshot</small>
```

**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

[![Screenshot Description](https://user-images.githubusercontent.com/40694158/42217798-4484e064-7ecf-11e8-9bd0-9d1390366f78.png)](https://staging.webcompat.com/uploads/2018/7/32fc44ad-2153-48ed-a85a-66040084c23c.jpg)

**Comment by softvision-sergiulogigan** [comment] 2018-07-03 14:20
Related to #2100

**Comment by miketaylr** [comment] 2018-07-05 22:07
I'm not 100% sure I understand the expected results. As-is, the text will be yellow if hovered or the area has focus (select "No" above it, then hit tab).

It's possible the addon is leaving focus?

**Comment by miketaylr** [comment] 2018-07-05 22:08
@softvision-sergiulogigan what are the circumstances or environment where the text is yellow by default? In my testing, it's all black (via the addon, or the built-in "report site issue" page action menu item in pre-release firefox).

**Comment by softvision-sergiulogigan** [comment] 2018-07-06 06:40
So this is on Beta 62, @miketaylr  :

![screen capture 1](https://user-images.githubusercontent.com/16573771/42363456-6f5ec538-8100-11e8-8f8a-2b867621d6c2.gif)

As you can see, the first time the text is black, and after manually uploading an image, the text is yellow.

**Comment by miketaylr** [comment] 2018-07-06 15:00
Thanks @softvision-sergiulogigan, I think the issue is somehow related to the preview area having focus after selecting the image (maybe a platform difference between mac/windows). 

I'm not very happy with the yellow or black text in general, depending on the screenshot it can be impossible to see. #2100 is related.

**Comment by miketaylr** [comment] 2018-07-06 15:07
I propose we close this, and just fix the parent issue by getting rid of the yellow/black floating text.

**Closed by miketaylr** 2018-07-06 15:07 UTC
