### ISSUE TITLE
New label "status: decision"

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1344] opened 2017-02-16 14:51 UTC
As partially my work is sometimes blocked by not finished discussions or not made decisions, I feel like a new label "status: needs decision" or "status: decision" would come handy.

I feel like we all make decisions together and I always appreciate the input from the team. Especially because I am new, I'd love not to make decisions all by myself and create chaos. :D

In addition, I am sure it would speed up the implementation of new ideas / small features like e.g. #1336 or #1338 or #1295 or #1284 etc. and make everyone aware of needed feedback.

Also, we could add a decision that was made (either mailing-list, IRC, meeting or through issue discussion and close the issue, open new follow up issue... probably this is the flow anyway.)

@adamopenweb @miketaylr @denschub @karlcow @MDTsai @magsout @wisniewskit

**Comment by magsout** [comment] 2017-02-16 15:49
@zoepage When I added new label few month ago, I had in my mind:

- Status: dicussion: discussion in progress
- Status : accepted -> accepted

It's not sufficient? What do you think?

**Comment by zoepage** [comment] 2017-02-16 15:52
@magsout Those labels are great :) I kind of miss an "urgent" or "let's make a decission and close this", because often the discussions dry up for various reasons. Or do you have a different idea? :)

**Comment by magsout** [comment] 2017-02-16 15:59
@zoepage no, I have the same feeling, not especially on Webcompat, but sometimes it's hard to know if everybody accept the issue or not ..

So I think when the author does not know the status of issue, he/she will throw a message  like, hey what's your opinions to closing or not the issue.

**Comment by zoepage** [comment] 2017-02-16 16:02
@magsout cool. :)

With a label everyone could filter like every 2 days if there is something really urgent they might have missed or every few days. 

So, you would basically add the label, ping everyone as you said and close after e.g. 48 hours?

**Comment by magsout** [comment] 2017-02-16 16:11
By closing, I was thinking about making a decision. 

I think if more than half member of webcompa say yes, we can say issue is accepted. Something like that IMHO.

Webcompat.com is not an official mozilla project as you know, so I think it's hard that everyone can spend time on it. It is true that some issue drag a little and take time to get

**Comment by adamopenweb** [comment] 2017-02-16 16:14
@zoepage If I understand this right, the problem is our decision making does not happen fast enough to allow you to build features? (And sometimes these features aren't very big.)

**Comment by zoepage** [comment] 2017-02-16 16:17
@magsout 
> By closing, I was thinking about making a decision.

I was thinking about something like a "last call". Does anyone have objections? Speak now or be quiet forever... 😁 

> Webcompat.com is not an official mozilla project as you know, so I think it's hard that everyone can spend time on it. It is true that some issue drag a little and take time to get

True, but when someone already expressed their point of view in that issue and it is very different from the to be made decision, this person can be pinged explicitly. But I think in 95% of the cases it will just be a reassurance if everyone is cool with it.

@adamopenweb 
>  the problem is our decision making does not happen fast enough

It's not about fast enough, more about the fact that it is unclear if there is one...?

**Comment by miketaylr** [comment] 2017-02-16 17:43
So what does the `status: decision` mean? It means a decision has been made? Or someone is requesting that one be made? Can we clarify that in the label: `status: needs decision`, if the former?

**Comment by karlcow** [comment] 2017-02-17 00:05
* Every 2 days seem too short. One week more reasonable. Some people can only contribute, specifically outside of Mozilla employees, a couple of hours a week.

Let's look at what were the issues mentioned by @zoepage 

* #1336 Opened 8 days ago. No hurry. it's a recent request. Nothing is breaking. And the discussion was going on until this morning. So here it's not a case of emergency.
* #1338 Opened 7 days ago. The discussion is still going on. Let me add a comment. 
* #1295 Opened 28 days ago. No emergency. There are things with more priorities. And it's not a small feature. When it will come to implement it. Specifically for grabbing the right information image and text. It needs to be discussed and probably around code in a PR.
* #1284 Opened on January 14. The next step here is someone proposing a wireframe and/or design  and a PR against this issue. There was no disagreement in the discussion.

So I'm happy we find a process for resolving decisions on issues. Probably more necessary now than it was in the future because we grew and less and less, it will be possible to discuss everything with everyone. It touches to a discussion we had with @miketaylr on module owners. 

There are different ways to "create consensus" aka a decision:

* Everyone agrees (long and can be demoralizing but at the same time can be a real empowerement of the community. Rust community style)
*  BDFL. Someone has the final say. (Python community style.) Not very fond of this model. It helps move forward faster, but the D still means Dictator.
* Guardian of the Galaxy aka module owners. For example in the past, the design was owned by @calexity Currently I would say the UX is owned my @mesha and the design is a bit up in the air. I did a bit with the form and @zoepage did a bit with the logo. The CSS/HTML is owned by @magsout The JavaScript probably by @miketaylr. The python probably @miketaylr and myself.
* No one disagrees before a reasonable date (W3C community style). This is a kind of what @zoepage is proposing. But I think giving a reasonable cut-off date and a clear way to ask in comments would help not missing any important information. It can be a syntax in the comment and would require to have a template for proposing features something along:

```
Short explicit summary: (title of the issue)
Description: (Explain what the proposal is with links to relevant part of the code, features, etc)
What does it solve?: (explain why we need it)
What are the steps to solve it?: (What it would require to modify, do to solve it)
```

By doing that, we would probably save a lot of discussions and misunderstandings. Then we could provide a reasonable timeline. `RFC until 2017-03-16` This can be a label `rfc-2017-03-16`. The good thing about deadlines is that they can be pushed away if required. (IETF-style with publishing a new draft). Making a decision on an issue, doesn't mean also it needs to be implemented right away. It just that we made a decision.

**Comment by zoepage** [comment] 2017-02-17 11:39
@miketaylr 
> We can also quickly review these in meetings 

Oh, great idea! :) In addition, if we don't have a meeting, everyone could spend those 10-15 minutes to check those issues? So we don't forget?


@miketaylr 
> I probably won't be looking at them every 2 days. 

@karlcow 
> Every 2 days seem too short. One week more reasonable. 

It was just an example. Every week is totally fine with me. :)


@karlcow 
> By doing that, we would probably save a lot of discussions and misunderstandings. [...] Making a decision on an issue, doesn't mean also it needs to be implemented right away. It just that we made a decision.

Fully agree!

**Comment by miketaylr** [comment] 2017-02-17 20:24
@zoepage want to make a "status: needs discussion" label? Seems like there's general consensus that it's a good idea.

@karlcow the idea around RFCs is a good one -- good topics for further discussion, and more broad that just signaling an issue needs some kind of decision made, or input. I'd probably want to study https://opensource.guide/leadership-and-governance/ a bit, but if you'd like to champion the formal definition of this process, that would be cool (also, a good topic for a work week or all hands or such).

**Comment by zoepage** [comment] 2017-02-17 20:25
@miketaylr I did, this morning :)

**Comment by miketaylr** [comment] 2017-02-17 20:32
lol nice

**Comment by miketaylr** [comment] 2017-02-17 20:32
lol nice

**Closed by miketaylr** 2017-02-17 20:32 UTC
Labels: status: discussion

**Comment by miketaylr** [comment] 2017-02-17 21:49
> I'd probably want to study https://opensource.guide/leadership-and-governance/ a bit

See also https://groups.google.com/d/msg/mozilla.dev.developer-tools/DaSOMXKFrsc/WHRCRRo8BQAJ

**Comment by magsout** [comment] 2017-02-17 21:55
> I'd probably want to study https://opensource.guide/leadership-and-governance/ a bit
See also https://groups.google.com/d/msg/mozilla.dev.developer-tools/DaSOMXKFrsc/WHRCRRo8BQAJ

Interesting ...
