### ISSUE TITLE
Proposal of html/js/css refactoring

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#1480] opened 2017-04-04 19:24 UTC
I would like to propose a redesign of webcompat, mainly on JavaScript. 

Currently, we use two libraries: 
- jQuery for manipulation of DOM and events
- Backbone for templates. 

I think it is quite possible to no longer use jQuery, modern browsers have a simple API to manipulate the DOM. 

Backbone, it plays very well its role of template, but, I found, it is difficult to make the code maintainable especially for new interfaces.

I had already spoken with @miketaylr  and @karlcow without opening an issue, so I would like to set up a new web stack with `React` for the UI, and `Redux` for the fetching.

I think React responses to several needs: everything is a component, the reuse of components, , testing of component, It also allows to use a server side with Python. The server can send HTML in response if needed (browser without javascript, first connection on the website, …).

Redux coupled with the api fetch, is a very simple solution and  a small library but powerful.

I propose this to set up these new libraries:

- Switch to webpack, tools needed for dependency, watch and build.
- removed all local dependencies (as jQuery, markdonw-it) and replaced by npm dependcies
- removed step by step Backbone template
  - new issues on homepage
  - list of issues and search form.
  - details of one issue
- removed jQuery and Backbone.
 
 Of course, I'm ok to work on it and try to propose something for the all hands. If all the teams agree. 
 
 If I propose this, is because I believe in React. I use it everyday on my job and I believe we can improve our code base, our UI, trust me;)

**Comment by karlcow** [comment] 2017-04-05 03:01
If this goes forward in any form and to avoid a mega issue. We could probably have a milestone with different small issues.

As you know I don't have a good opinion about React. The concept seems interesting on paper, but I haven't seen one Web site using React doing a good job in terms of HTML/CSS and semantics. (Note that I don't think the current webcompat does well :) ) I'm happy to see examples of what is considered good react web sites. I guess I'm unlucky because of webcompat broken web sites debugging.

I also would love us to explore the possibility in parallel to fetch more things on the python side so we have an already populated page with data and use JavaScript (be a framework or not) to manage the secondary interactions. 

We should also probably set a goal of measuring the current performances of the site and see if our modifications improve the speed or not.

**Comment by zoepage** [comment] 2017-04-05 09:24
@magsout 
I like the idea of moving the front-end to React.
(Last app I've build was also a refactor from Backbone to React. It was a smooth move.)

@karlcow 
> If this goes forward in any form and to avoid a mega issue. We could probably have a milestone with different small issues.

+1

> I also would love us to explore the possibility in parallel to fetch more things on the python side so we have an already populated page with data and use JavaScript (be a framework or not) to manage the secondary interactions.

+1

> We should also probably set a goal of measuring the current performances of the site and see if our modifications improve the speed or not.

+1

Before we can start with this, I feel like some things should to happen first.
With the proposed changes from @lockettm, we'll add new content and probably also refactor the site structure a bit. So, without not knowing 100% on what will change and what our needs are, it might end up bit messy doing the refactor. This is at least what I am mostly concerned about. 

I also made good experience with first straightening up the design as it is great, but through adding features, content and time, not consistent (e.g. #1442). The CSS also grew over time, because of the same reasons. It would be the perfect time to clean it up and make it more modular (which would also prep it to move to react components in a more clean and structured way). Adding a [living style guide](https://www.smashingmagazine.com/2016/05/creating-a-living-style-guide-case-study/) like started [here](http://webcompat.github.io/webcompat.com/), would give new contributors also more insights how to build new features or visually test our CSS (we could even automate it at some point with visual regression testing) plus working on HTML semantics.

After those steps, we would have a really good base for a JS refactor, I guess.

So, summed up I would like to suggest following steps before the JS refactor:

- Crafting new content for the website and a new site structure
- Straightening up the design and make it more consistent
- Clean up and document CSS (with living styleguide)

We could prepare everything until the work week in SF and hack on it. Also could start with a concept and todos for the JS refactor there and talk about what needs to be moved to the Python side / architecture.

(I've worked on a more detailed concept for the past few weeks and am happy to share soon.)

**Comment by miketaylr** [comment] 2017-04-05 17:52
I like the idea of coordinating @zoepage's suggestions and this proposal. It sounds like a lot of great improvement in terms of site structure/content/tech. And a lot of cool things to hack on in SF. :)

**Comment by karlcow** [comment] 2017-04-06 00:40
> probably also refactor the site structure a bit.

I will be keeping an eye on this one. [Cool URIs don't change](https://www.w3.org/Provider/Style/URI) 😁

**Comment by magsout** [comment] 2017-04-26 08:09
thanks @karlcow @zoepage @miketaylr for your feedback.

**Comment by zoepage** [comment] 2017-07-06 23:28
As we are progressing with the refactor, I'd like to close this one and re-visit when we are finally at the JS refactor stage. What do you think @magsout ?

**Comment by zoepage** [comment] 2017-08-01 15:59
Closing and adding the backlog label, so we can revisit.

**Closed by zoepage** 2017-08-01 15:59 UTC
Labels: lang: CSS, lang: HTML, lang: JS, scope: refactor
