### ISSUE TITLE
google search for webcompat page leads to cert error

### ISSUE THREAD

**Issue by philipp-sumo** [webcompat/webcompat.com#2822] opened 2019-03-19 18:20 UTC
![grafik](https://user-images.githubusercontent.com/1524147/54631190-c51dad00-4a7b-11e9-9a55-81672ef6e7b8.png)
the first google result for the term "webcompat" is https://www.webcompat.com/ which leads to a SSL_ERROR_BAD_CERT_DOMAIN cert error due to the www in front of the domain name.

**Comment by karlcow** [comment] 2019-04-24 05:18
Duplicate of #2780 

@philipp-sumo thanks for the report. This is a known issue.

**Closed by karlcow** 2019-04-24 05:18 UTC

**Comment by miketaylr** [comment] 2019-05-06 16:30
This is fixed now, thanks for reporting!
