### ISSUE TITLE
Add vars to media-queries

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#2314] opened 2018-03-28 09:47 UTC
https://www.npmjs.com/package/postcss-media-variables

**Comment by zoepage** [comment] 2018-03-28 10:12
This is failing for me, so lets postpone that issue as its not blocking. If anyone wants to take over, feel free. :)

**Comment by magsout** [comment] 2018-03-28 18:20
After updated `postcss-*` and added `postcss-media-variables`

```
Running "watch" task
Waiting...
>> File "webcompat/static/css/src/grid.css" changed.
Running "postcss:dist" (postcss) task
Node#before is deprecated. Use Node#raws.before
>> 1 processed stylesheet created.

Done.
```

So I think there is a package which is not updated for the postcss version 6..

**Comment by magsout** [comment] 2018-03-28 18:27
I'm reading that https://github.com/postcss/postcss-custom-properties/issues/24 and https://github.com/MoOx/postcss-cssnext/issues/253

Not sure it's a good idea to add this kind of plugin.

@zoepage @miketaylr ?

**Comment by magsout** [comment] 2018-03-28 18:32
Maybe we can just add `custom-media-queries` in `variables.css` and let the comment to rely on the `var(--page-size-m)` like this 
```
// rely on var(--page-size-m)
@custom-media --page-min-size-m (max-width: 665px);
```

and use as:

```
@media (--page-min-size-m) {
  .grid-row {
    margin: 0 calc(-1 / 2 * var(--unit-space)) var(--grid-outermargin-m);
  }

  .grid-show-gap .grid-cell {
    margin-bottom: var(--grid-outermargin-m);
  }

  .x1-fix {
    max-width: var(--unit-modul-s);
  }
}
```

**Comment by miketaylr** [comment] 2018-03-30 18:41
Yeah, I dunno. If it's a current limitation of CSS, maybe it's just better to live with it.

**Comment by magsout** [comment] 2018-03-30 19:08
@miketaylr the good thing, we can update postcss with latest versions without error ;)

**Comment by magsout** [comment] 2018-04-18 18:08
@Regaddi to clarify my comments, I'm not a big fan of Sass, not anymore, I used Sass  couple of years.

The question is What can we do with Sass we can not do with css? 

IMO, Sass is motly another layer writing a subset of css. it helps writing css wich is repeating but that's it.

**Comment by Regaddi** [comment] 2018-04-18 18:42
> The question is What can we do with Sass we can not do with css?
We can use vars in or for media queries and solve this issue 😅 

Joking aside, CSS has matured a lot in the last few years and I'm really happy about this evolution. One thing that I still dislike is that I have to repeat parts of my selectors over and over again. But this is probably just personally. If I have the opportunity to do the same thing with less code, why not? 😄 

So basically yes, Sass is mostly another layer of CSS, but IMO a pretty convenient one for developers.

**Comment by miketaylr** [comment] 2018-04-24 14:34
To me it feels like switching to SASS to solve this one issue feels like a bit much. I'm a respectful -1, though I appreciate the PR and contribution from @Regaddi.

**Comment by Regaddi** [comment] 2018-04-24 15:46
@miketaylr It is not really solely solving this particular issue. With Sass we're able to establish a clean stylesheet architecture, which can't be achieved with pure CSS in a satisfying way. Sass allows to strictly divide the stylesheet code into configurational, reusable and applying parts. It allows to e.g. abstract the styles for labels without duplicating CSS code (as we currently do). So for this particular issue here the switch seems like a big cannonball, but in the long-term I can see great advantages.

**Comment by zoepage** [comment] 2018-04-24 15:57
The biggest advantage I see it the normalisation of margins / paddings and gaps between the grid elements through functions that can live in one place and be reused. solving the breakpoints issue is a bonus for me.

**Comment by miketaylr** [comment] 2018-04-25 17:26
> With Sass we're able to establish a clean stylesheet architecture, which can't be achieved with pure CSS in a satisfying way.

This feels a bit subjective, since clean and satisfying mean different things to each of us. :)

> Sass allows to strictly divide the stylesheet code into configurational, reusable and applying parts.

Yeah, this could be good. I feel like we should consider this at some point, and maybe collect concrete use cases for it now, but I don't see that we need it today.

Related, https://engineering.linkedin.com/blog/2018/04/css-at-scale--linkedins-new-open-source-projects-take-on-stylesh is an interesting read. Obviously we're not at LinkedIn scale, but they list some problems they had with bloat caused by using Sass mixins and the like.

**Comment by miketaylr** [comment] 2018-09-24 22:57
I'm going to WONTFIX this, we can revisit if we feel like we need it.

**Closed by miketaylr** 2018-09-24 22:57 UTC
Labels: in progress, lang: CSS, scope: refactor
