### ISSUE TITLE
Cursor doesn't change when hovering over the "previous" and "next" buttons

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2156] opened 2018-02-19 13:29 UTC
**Environment:**
Browser / Version: Chrome 64.0.3282.167 (Desktop), Firefox Nightly 60.0a1 (Desktop)
Operating System: Windows 10

**Steps to Reproduce:**
1. Go to https://staging.webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc
2. Hover over the "previous" and "next" buttons.

**Expected Behavior:**
The cursor changes shape into a hand.

**Actual Behavior:**
The cursor does not change shape.

**Notes:**
1. Screen capture attached.

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

![screen capture](https://user-images.githubusercontent.com/16573771/36379768-859dbb9e-1588-11e8-9878-0ed7631b263b.gif)

**Comment by magsout** [comment] 2018-02-19 17:03
dupe of #2069 
Fixed by https://github.com/webcompat/webcompat.com/pull/2129

**Closed by magsout** 2018-02-19 17:03 UTC
Labels: prio: good next bug, scope: refactor, type: bug
