### ISSUE TITLE
Selecting "Other" from browser selection presents an interesting text field [New UI]

### ISSUE THREAD

**Issue by mcroud** [webcompat/webcompat.com#2974] opened 2019-10-11 15:37 UTC
On step 4 (testing), when I select Other, I should be presented with a text field labelled "Browser tested" featuring the placeholder text "Browser"

<img width="1007" alt="Screenshot 2019-10-11 at 16 33 40" src="https://user-images.githubusercontent.com/42435754/66664684-e840c180-ec44-11e9-970f-7a5fd018b339.png">

What I get is an non-interactive text field with Yes/No values:
 
<img width="1082" alt="Screenshot 2019-10-11 at 16 34 27" src="https://user-images.githubusercontent.com/42435754/66664736-04446300-ec45-11e9-9631-dc101a9d684c.png">

**Comment by bacharakis** [comment] 2019-10-14 12:13
Due to report limitations, in that specific case, we can't ask the version of the browser tested. 
The UI should just keep the value that "tested to other browsers" and that's it as in other selections.

**Comment by johngian** [comment] 2019-10-14 14:55
Hi! I gave a quick look. Currently webcompat report doesn't have a field for the browser users reproduced the bug (it's just a boolean yes/no). The idea is that for now this should be translated to the clientside logic to the current report field.

**Comment by bacharakis** [comment] 2019-10-21 15:11
Assigned to @munteanu210

**Comment by munteanu210** [comment] 2019-10-22 18:15
I fixed this in PR #3010. So as the existing back end does not accept values other than Yes / No for "Did you test in another browser?", I made the new bug form send the value "Yes" to the server when selecting a browser, and send the value "No" to the server when the user selects "I have only tested on this browser". See screenshot below:

![browser-yes-no](https://user-images.githubusercontent.com/1682059/67316342-1af87e80-f4bd-11e9-9d31-f7b620fb0f7c.png)

**Closed** 2019-10-22 20:43 UTC
Labels: prio: important
