### ISSUE TITLE
The status-needstriage label is added and removed after filing an issue

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#1553] opened 2017-05-10 14:24 UTC
Browser / Version: Chrome 57.0.2987.133 (Desktop)
Operating System: Windows 10

**Steps to Reproduce:**
1. Navigate to: https://github.com/webcompat/web-bugs/issues/6591.
2. Observe the labels assigned.

**Expected Behavior:**
The status-needstriage label is applied.

**Actual Behavior:**
The status-needstriage label is applied and then removed.

**Notes:**
1. The issue is also reproducible for https://github.com/webcompat/web-bugs/issues/6580

sv;
![screenshot_1](https://cloud.githubusercontent.com/assets/16573771/25903572/78ee2780-35a5-11e7-963c-cb0d2a3f18fa.png)

**Comment by softvision-sergiulogigan** [comment] 2017-05-11 08:36
Could this be related to https://github.com/webcompat/webcompat.com/issues/1228 ?

**Comment by karlcow** [comment] 2017-05-12 01:08
@softvision-sergiulogigan I'm inclined to think that's the case. I will come up with something in #1228 
As for now I will close this one as a duplicate of the other and we will see if my modifications are working.

**Closed by karlcow** 2017-05-12 01:08 UTC
